<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 13 Ensemble Learning | Toolbox for Social Scientists and Policy Analysts</title>
  <meta name="description" content="Chapter 13 Ensemble Learning | Toolbox for Social Scientists and Policy Analysts" />
  <meta name="generator" content="bookdown 0.32.1 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 13 Ensemble Learning | Toolbox for Social Scientists and Policy Analysts" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://yaydede.github.io/toolbox//png/cover2.png" />
  
  <meta name="github-repo" content="yaydede/ToolShed_draft" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 13 Ensemble Learning | Toolbox for Social Scientists and Policy Analysts" />
  
  
  <meta name="twitter:image" content="https://yaydede.github.io/toolbox//png/cover2.png" />

<meta name="author" content="Yigit Aydede" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="cart.html"/>
<link rel="next" href="ensemble-applications.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Toolbox</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#who"><i class="fa fa-check"></i>Who</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#license"><i class="fa fa-check"></i>License</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> How we define Machine Learning</a></li>
<li class="chapter" data-level="2" data-path="preliminaries.html"><a href="preliminaries.html"><i class="fa fa-check"></i><b>2</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="2.1" data-path="preliminaries.html"><a href="preliminaries.html#data-and-dataset-types"><i class="fa fa-check"></i><b>2.1</b> Data and dataset types</a></li>
<li class="chapter" data-level="2.2" data-path="preliminaries.html"><a href="preliminaries.html#plots"><i class="fa fa-check"></i><b>2.2</b> Plots</a></li>
<li class="chapter" data-level="2.3" data-path="preliminaries.html"><a href="preliminaries.html#probability-distributions-with-r"><i class="fa fa-check"></i><b>2.3</b> Probability Distributions with R</a></li>
<li class="chapter" data-level="2.4" data-path="preliminaries.html"><a href="preliminaries.html#regressions"><i class="fa fa-check"></i><b>2.4</b> Regressions</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="preliminaries.html"><a href="preliminaries.html#ordinary-least-squares-ols"><i class="fa fa-check"></i><b>2.4.1</b> Ordinary Least Squares (OLS)</a></li>
<li class="chapter" data-level="2.4.2" data-path="preliminaries.html"><a href="preliminaries.html#maximum-likelihood-estimators"><i class="fa fa-check"></i><b>2.4.2</b> Maximum Likelihood Estimators</a></li>
<li class="chapter" data-level="2.4.3" data-path="preliminaries.html"><a href="preliminaries.html#estimating-mle-with-r"><i class="fa fa-check"></i><b>2.4.3</b> Estimating MLE with R</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="preliminaries.html"><a href="preliminaries.html#blue"><i class="fa fa-check"></i><b>2.5</b> BLUE</a></li>
<li class="chapter" data-level="2.6" data-path="preliminaries.html"><a href="preliminaries.html#modeling-the-data"><i class="fa fa-check"></i><b>2.6</b> Modeling the data</a></li>
<li class="chapter" data-level="2.7" data-path="preliminaries.html"><a href="preliminaries.html#causal-vs.-predictive-models"><i class="fa fa-check"></i><b>2.7</b> Causal vs. Predictive Models</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="preliminaries.html"><a href="preliminaries.html#causal-models"><i class="fa fa-check"></i><b>2.7.1</b> Causal Models</a></li>
<li class="chapter" data-level="2.7.2" data-path="preliminaries.html"><a href="preliminaries.html#predictive-models"><i class="fa fa-check"></i><b>2.7.2</b> Predictive Models</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="preliminaries.html"><a href="preliminaries.html#simulation"><i class="fa fa-check"></i><b>2.8</b> Simulation</a></li>
</ul></li>
<li class="part"><span><b>I Formal Look at Prediction</b></span></li>
<li class="chapter" data-level="" data-path="learning-systems.html"><a href="learning-systems.html"><i class="fa fa-check"></i>Learning Systems</a></li>
<li class="chapter" data-level="3" data-path="bias-variance-tradeoff.html"><a href="bias-variance-tradeoff.html"><i class="fa fa-check"></i><b>3</b> Bias-Variance Tradeoff</a>
<ul>
<li class="chapter" data-level="3.1" data-path="bias-variance-tradeoff.html"><a href="bias-variance-tradeoff.html#estimator-and-mse"><i class="fa fa-check"></i><b>3.1</b> Estimator and MSE</a></li>
<li class="chapter" data-level="3.2" data-path="bias-variance-tradeoff.html"><a href="bias-variance-tradeoff.html#prediction---mspe"><i class="fa fa-check"></i><b>3.2</b> Prediction - MSPE</a></li>
<li class="chapter" data-level="3.3" data-path="bias-variance-tradeoff.html"><a href="bias-variance-tradeoff.html#biased-estimator-as-a-predictor"><i class="fa fa-check"></i><b>3.3</b> Biased estimator as a predictor</a></li>
<li class="chapter" data-level="3.4" data-path="bias-variance-tradeoff.html"><a href="bias-variance-tradeoff.html#dropping-a-variable-in-a-regression"><i class="fa fa-check"></i><b>3.4</b> Dropping a variable in a regression</a></li>
<li class="chapter" data-level="3.5" data-path="bias-variance-tradeoff.html"><a href="bias-variance-tradeoff.html#uncertainty-in-estimations-and-predictions"><i class="fa fa-check"></i><b>3.5</b> Uncertainty in estimations and predictions</a></li>
<li class="chapter" data-level="3.6" data-path="bias-variance-tradeoff.html"><a href="bias-variance-tradeoff.html#prediction-interval-for-unbiased-ols-predictor"><i class="fa fa-check"></i><b>3.6</b> Prediction interval for unbiased OLS predictor</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="overfitting.html"><a href="overfitting.html"><i class="fa fa-check"></i><b>4</b> Overfitting</a></li>
<li class="part"><span><b>II Nonparametric Estimations</b></span></li>
<li class="chapter" data-level="" data-path="parametric-vs.-nonparametric-methods.html"><a href="parametric-vs.-nonparametric-methods.html"><i class="fa fa-check"></i>Parametric vs. Nonparametric methods</a></li>
<li class="chapter" data-level="5" data-path="parametric-estimations.html"><a href="parametric-estimations.html"><i class="fa fa-check"></i><b>5</b> Parametric Estimations</a>
<ul>
<li class="chapter" data-level="5.1" data-path="parametric-estimations.html"><a href="parametric-estimations.html#linear-probability-models-lpm"><i class="fa fa-check"></i><b>5.1</b> Linear Probability Models (LPM)</a></li>
<li class="chapter" data-level="5.2" data-path="parametric-estimations.html"><a href="parametric-estimations.html#logistic-regression"><i class="fa fa-check"></i><b>5.2</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="parametric-estimations.html"><a href="parametric-estimations.html#estimating-logistic-regression"><i class="fa fa-check"></i><b>5.2.1</b> Estimating Logistic Regression</a></li>
<li class="chapter" data-level="5.2.2" data-path="parametric-estimations.html"><a href="parametric-estimations.html#cost-functions"><i class="fa fa-check"></i><b>5.2.2</b> Cost functions</a></li>
<li class="chapter" data-level="5.2.3" data-path="parametric-estimations.html"><a href="parametric-estimations.html#deviance"><i class="fa fa-check"></i><b>5.2.3</b> Deviance</a></li>
<li class="chapter" data-level="5.2.4" data-path="parametric-estimations.html"><a href="parametric-estimations.html#predictive-accuracy"><i class="fa fa-check"></i><b>5.2.4</b> Predictive accuracy</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="nonparametric-estimations---basics.html"><a href="nonparametric-estimations---basics.html"><i class="fa fa-check"></i><b>6</b> Nonparametric Estimations - Basics</a>
<ul>
<li class="chapter" data-level="6.1" data-path="nonparametric-estimations---basics.html"><a href="nonparametric-estimations---basics.html#density-estimations"><i class="fa fa-check"></i><b>6.1</b> Density Estimations</a></li>
<li class="chapter" data-level="6.2" data-path="nonparametric-estimations---basics.html"><a href="nonparametric-estimations---basics.html#kernel-regressions"><i class="fa fa-check"></i><b>6.2</b> Kernel regressions</a></li>
<li class="chapter" data-level="6.3" data-path="nonparametric-estimations---basics.html"><a href="nonparametric-estimations---basics.html#regression-splines"><i class="fa fa-check"></i><b>6.3</b> Regression Splines</a></li>
<li class="chapter" data-level="6.4" data-path="nonparametric-estimations---basics.html"><a href="nonparametric-estimations---basics.html#mars---multivariate-adaptive-regression-splines"><i class="fa fa-check"></i><b>6.4</b> MARS - Multivariate Adaptive Regression Splines</a></li>
<li class="chapter" data-level="6.5" data-path="nonparametric-estimations---basics.html"><a href="nonparametric-estimations---basics.html#gam---generalized-additive-model"><i class="fa fa-check"></i><b>6.5</b> GAM - Generalized Additive Model</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="smoothing.html"><a href="smoothing.html"><i class="fa fa-check"></i><b>7</b> Smoothing</a>
<ul>
<li class="chapter" data-level="7.1" data-path="smoothing.html"><a href="smoothing.html#using-bins"><i class="fa fa-check"></i><b>7.1</b> Using bins</a></li>
<li class="chapter" data-level="7.2" data-path="smoothing.html"><a href="smoothing.html#kernel-smoothing"><i class="fa fa-check"></i><b>7.2</b> Kernel smoothing</a></li>
<li class="chapter" data-level="7.3" data-path="smoothing.html"><a href="smoothing.html#locally-weighted-regression-loess"><i class="fa fa-check"></i><b>7.3</b> Locally weighted regression <code>loess()</code></a></li>
<li class="chapter" data-level="7.4" data-path="smoothing.html"><a href="smoothing.html#smooth-spline-regression"><i class="fa fa-check"></i><b>7.4</b> Smooth Spline Regression</a></li>
<li class="chapter" data-level="7.5" data-path="smoothing.html"><a href="smoothing.html#multivariate-loess"><i class="fa fa-check"></i><b>7.5</b> Multivariate Loess</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="nonparametric-classifier---knn.html"><a href="nonparametric-classifier---knn.html"><i class="fa fa-check"></i><b>8</b> Nonparametric Classifier - kNN</a>
<ul>
<li class="chapter" data-level="8.1" data-path="nonparametric-classifier---knn.html"><a href="nonparametric-classifier---knn.html#mnist-dataset"><i class="fa fa-check"></i><b>8.1</b> <code>mnist</code> Dataset</a></li>
<li class="chapter" data-level="8.2" data-path="nonparametric-classifier---knn.html"><a href="nonparametric-classifier---knn.html#linear-classifiers-again"><i class="fa fa-check"></i><b>8.2</b> Linear classifiers (again)</a></li>
<li class="chapter" data-level="8.3" data-path="nonparametric-classifier---knn.html"><a href="nonparametric-classifier---knn.html#k-nearest-neighbors"><i class="fa fa-check"></i><b>8.3</b> k-Nearest Neighbors</a></li>
<li class="chapter" data-level="8.4" data-path="nonparametric-classifier---knn.html"><a href="nonparametric-classifier---knn.html#knn-with-caret"><i class="fa fa-check"></i><b>8.4</b> kNN with caret</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="nonparametric-classifier---knn.html"><a href="nonparametric-classifier---knn.html#mnist_27"><i class="fa fa-check"></i><b>8.4.1</b> <code>mnist_27</code></a></li>
<li class="chapter" data-level="8.4.2" data-path="nonparametric-classifier---knn.html"><a href="nonparametric-classifier---knn.html#adult-dataset"><i class="fa fa-check"></i><b>8.4.2</b> Adult dataset</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>III Self-Learning</b></span></li>
<li class="chapter" data-level="9" data-path="hyperparameter-tuning.html"><a href="hyperparameter-tuning.html"><i class="fa fa-check"></i><b>9</b> Hyperparameter Tuning</a>
<ul>
<li class="chapter" data-level="9.1" data-path="hyperparameter-tuning.html"><a href="hyperparameter-tuning.html#training-validation-and-test-datasets"><i class="fa fa-check"></i><b>9.1</b> Training, validation, and test datasets</a></li>
<li class="chapter" data-level="9.2" data-path="hyperparameter-tuning.html"><a href="hyperparameter-tuning.html#splitting-the-data-randomly"><i class="fa fa-check"></i><b>9.2</b> Splitting the data randomly</a></li>
<li class="chapter" data-level="9.3" data-path="hyperparameter-tuning.html"><a href="hyperparameter-tuning.html#k-fold-cross-validation"><i class="fa fa-check"></i><b>9.3</b> k-fold cross validation</a></li>
<li class="chapter" data-level="9.4" data-path="hyperparameter-tuning.html"><a href="hyperparameter-tuning.html#cross-validated-grid-search"><i class="fa fa-check"></i><b>9.4</b> Cross-validated grid search</a></li>
<li class="chapter" data-level="9.5" data-path="hyperparameter-tuning.html"><a href="hyperparameter-tuning.html#bootstrapped-grid-search"><i class="fa fa-check"></i><b>9.5</b> Bootstrapped grid search</a></li>
<li class="chapter" data-level="9.6" data-path="hyperparameter-tuning.html"><a href="hyperparameter-tuning.html#when-the-data-is-time-series"><i class="fa fa-check"></i><b>9.6</b> When the data is time-series</a></li>
<li class="chapter" data-level="9.7" data-path="hyperparameter-tuning.html"><a href="hyperparameter-tuning.html#speed"><i class="fa fa-check"></i><b>9.7</b> Speed</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="tuning-in-classification.html"><a href="tuning-in-classification.html"><i class="fa fa-check"></i><b>10</b> Tuning in Classification</a>
<ul>
<li class="chapter" data-level="10.1" data-path="tuning-in-classification.html"><a href="tuning-in-classification.html#confusion-matrix"><i class="fa fa-check"></i><b>10.1</b> Confusion matrix</a></li>
<li class="chapter" data-level="10.2" data-path="tuning-in-classification.html"><a href="tuning-in-classification.html#performance-measures"><i class="fa fa-check"></i><b>10.2</b> Performance measures</a></li>
<li class="chapter" data-level="10.3" data-path="tuning-in-classification.html"><a href="tuning-in-classification.html#roc-curve"><i class="fa fa-check"></i><b>10.3</b> ROC Curve</a></li>
<li class="chapter" data-level="10.4" data-path="tuning-in-classification.html"><a href="tuning-in-classification.html#auc---area-under-the-curve"><i class="fa fa-check"></i><b>10.4</b> AUC - Area Under the Curve</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="classification-example.html"><a href="classification-example.html"><i class="fa fa-check"></i><b>11</b> Classification Example</a>
<ul>
<li class="chapter" data-level="11.1" data-path="classification-example.html"><a href="classification-example.html#lpm"><i class="fa fa-check"></i><b>11.1</b> LPM</a></li>
<li class="chapter" data-level="11.2" data-path="classification-example.html"><a href="classification-example.html#logistic-regression-1"><i class="fa fa-check"></i><b>11.2</b> Logistic Regression</a></li>
<li class="chapter" data-level="11.3" data-path="classification-example.html"><a href="classification-example.html#knn"><i class="fa fa-check"></i><b>11.3</b> kNN</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="classification-example.html"><a href="classification-example.html#knn-10-fold-cv"><i class="fa fa-check"></i><b>11.3.1</b> kNN 10-fold CV</a></li>
<li class="chapter" data-level="11.3.2" data-path="classification-example.html"><a href="classification-example.html#knn-with-caret-1"><i class="fa fa-check"></i><b>11.3.2</b> kNN with <code>caret</code></a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV Tree-based Models</b></span></li>
<li class="chapter" data-level="12" data-path="cart.html"><a href="cart.html"><i class="fa fa-check"></i><b>12</b> CART</a>
<ul>
<li class="chapter" data-level="12.1" data-path="cart.html"><a href="cart.html#cart---classification-tree"><i class="fa fa-check"></i><b>12.1</b> CART - Classification Tree</a></li>
<li class="chapter" data-level="12.2" data-path="cart.html"><a href="cart.html#rpart---recursive-partitioning"><i class="fa fa-check"></i><b>12.2</b> <code>rpart</code> - Recursive Partitioning</a></li>
<li class="chapter" data-level="12.3" data-path="cart.html"><a href="cart.html#pruning"><i class="fa fa-check"></i><b>12.3</b> Pruning</a></li>
<li class="chapter" data-level="12.4" data-path="cart.html"><a href="cart.html#classification-with-titanic"><i class="fa fa-check"></i><b>12.4</b> Classification with Titanic</a></li>
<li class="chapter" data-level="12.5" data-path="cart.html"><a href="cart.html#regression-tree"><i class="fa fa-check"></i><b>12.5</b> Regression Tree</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="ensemble-learning.html"><a href="ensemble-learning.html"><i class="fa fa-check"></i><b>13</b> Ensemble Learning</a>
<ul>
<li class="chapter" data-level="13.1" data-path="ensemble-learning.html"><a href="ensemble-learning.html#bagging"><i class="fa fa-check"></i><b>13.1</b> Bagging</a></li>
<li class="chapter" data-level="13.2" data-path="ensemble-learning.html"><a href="ensemble-learning.html#random-forest"><i class="fa fa-check"></i><b>13.2</b> Random Forest</a></li>
<li class="chapter" data-level="13.3" data-path="ensemble-learning.html"><a href="ensemble-learning.html#boosting"><i class="fa fa-check"></i><b>13.3</b> Boosting</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="ensemble-learning.html"><a href="ensemble-learning.html#sequential-ensemble-with-gbm"><i class="fa fa-check"></i><b>13.3.1</b> Sequential ensemble with <code>gbm</code></a></li>
<li class="chapter" data-level="13.3.2" data-path="ensemble-learning.html"><a href="ensemble-learning.html#adaboost"><i class="fa fa-check"></i><b>13.3.2</b> AdaBoost</a></li>
<li class="chapter" data-level="13.3.3" data-path="ensemble-learning.html"><a href="ensemble-learning.html#xgboost"><i class="fa fa-check"></i><b>13.3.3</b> XGBoost</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="ensemble-applications.html"><a href="ensemble-applications.html"><i class="fa fa-check"></i><b>14</b> Ensemble Applications</a>
<ul>
<li class="chapter" data-level="14.1" data-path="ensemble-applications.html"><a href="ensemble-applications.html#classification"><i class="fa fa-check"></i><b>14.1</b> Classification</a></li>
<li class="chapter" data-level="14.2" data-path="ensemble-applications.html"><a href="ensemble-applications.html#regression"><i class="fa fa-check"></i><b>14.2</b> Regression</a></li>
<li class="chapter" data-level="14.3" data-path="ensemble-applications.html"><a href="ensemble-applications.html#exploration"><i class="fa fa-check"></i><b>14.3</b> Exploration</a></li>
<li class="chapter" data-level="14.4" data-path="ensemble-applications.html"><a href="ensemble-applications.html#boosting-applications"><i class="fa fa-check"></i><b>14.4</b> Boosting Applications</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="ensemble-applications.html"><a href="ensemble-applications.html#regression-1"><i class="fa fa-check"></i><b>14.4.1</b> Regression</a></li>
<li class="chapter" data-level="14.4.2" data-path="ensemble-applications.html"><a href="ensemble-applications.html#random-search-with-parallel-processing"><i class="fa fa-check"></i><b>14.4.2</b> Random search with parallel processing</a></li>
<li class="chapter" data-level="14.4.3" data-path="ensemble-applications.html"><a href="ensemble-applications.html#boosting-vs.-others"><i class="fa fa-check"></i><b>14.4.3</b> Boosting vs. Others</a></li>
<li class="chapter" data-level="14.4.4" data-path="ensemble-applications.html"><a href="ensemble-applications.html#classification-1"><i class="fa fa-check"></i><b>14.4.4</b> Classification</a></li>
<li class="chapter" data-level="14.4.5" data-path="ensemble-applications.html"><a href="ensemble-applications.html#adaboost.m1"><i class="fa fa-check"></i><b>14.4.5</b> AdaBoost.M1</a></li>
<li class="chapter" data-level="14.4.6" data-path="ensemble-applications.html"><a href="ensemble-applications.html#classification-with-xgboost"><i class="fa fa-check"></i><b>14.4.6</b> Classification with XGBoost</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>V SVM &amp; Neural Networks</b></span></li>
<li class="chapter" data-level="15" data-path="support-vector-machines.html"><a href="support-vector-machines.html"><i class="fa fa-check"></i><b>15</b> Support Vector Machines</a>
<ul>
<li class="chapter" data-level="15.1" data-path="support-vector-machines.html"><a href="support-vector-machines.html#optimal-separating-classifier"><i class="fa fa-check"></i><b>15.1</b> Optimal Separating Classifier</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="support-vector-machines.html"><a href="support-vector-machines.html#the-margin"><i class="fa fa-check"></i><b>15.1.1</b> The Margin</a></li>
<li class="chapter" data-level="15.1.2" data-path="support-vector-machines.html"><a href="support-vector-machines.html#the-non-separable-case"><i class="fa fa-check"></i><b>15.1.2</b> The Non-Separable Case</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="support-vector-machines.html"><a href="support-vector-machines.html#nonlinear-boundary-with-kernels"><i class="fa fa-check"></i><b>15.2</b> Nonlinear Boundary with Kernels</a></li>
<li class="chapter" data-level="15.3" data-path="support-vector-machines.html"><a href="support-vector-machines.html#application-with-svm"><i class="fa fa-check"></i><b>15.3</b> Application with SVM</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="artificial-neural-networks.html"><a href="artificial-neural-networks.html"><i class="fa fa-check"></i><b>16</b> Artificial Neural Networks</a>
<ul>
<li class="chapter" data-level="16.1" data-path="artificial-neural-networks.html"><a href="artificial-neural-networks.html#neural-network---the-idea"><i class="fa fa-check"></i><b>16.1</b> Neural Network - the idea</a></li>
<li class="chapter" data-level="16.2" data-path="artificial-neural-networks.html"><a href="artificial-neural-networks.html#backpropagation"><i class="fa fa-check"></i><b>16.2</b> Backpropagation</a></li>
<li class="chapter" data-level="16.3" data-path="artificial-neural-networks.html"><a href="artificial-neural-networks.html#neural-network---more-inputs"><i class="fa fa-check"></i><b>16.3</b> Neural Network - More inputs</a></li>
<li class="chapter" data-level="16.4" data-path="artificial-neural-networks.html"><a href="artificial-neural-networks.html#deep-learning"><i class="fa fa-check"></i><b>16.4</b> Deep Learning</a></li>
</ul></li>
<li class="part"><span><b>VI Penalized Regressions</b></span></li>
<li class="chapter" data-level="" data-path="parametric-models-in-prediction.html"><a href="parametric-models-in-prediction.html"><i class="fa fa-check"></i>Parametric models in prediction</a></li>
<li class="chapter" data-level="17" data-path="ridge.html"><a href="ridge.html"><i class="fa fa-check"></i><b>17</b> Ridge</a></li>
<li class="chapter" data-level="18" data-path="lasso.html"><a href="lasso.html"><i class="fa fa-check"></i><b>18</b> Lasso</a></li>
<li class="chapter" data-level="19" data-path="adaptive-lasso.html"><a href="adaptive-lasso.html"><i class="fa fa-check"></i><b>19</b> Adaptive Lasso</a></li>
<li class="chapter" data-level="20" data-path="sparsity.html"><a href="sparsity.html"><i class="fa fa-check"></i><b>20</b> Sparsity</a></li>
<li class="part"><span><b>VII Time Series</b></span></li>
<li class="chapter" data-level="" data-path="forecasting.html"><a href="forecasting.html"><i class="fa fa-check"></i>Forecasting</a></li>
<li class="chapter" data-level="21" data-path="arima-models.html"><a href="arima-models.html"><i class="fa fa-check"></i><b>21</b> ARIMA models</a>
<ul>
<li class="chapter" data-level="21.1" data-path="arima-models.html"><a href="arima-models.html#hyndman-khandakar-algorithm"><i class="fa fa-check"></i><b>21.1</b> Hyndman-Khandakar algorithm</a></li>
<li class="chapter" data-level="21.2" data-path="arima-models.html"><a href="arima-models.html#ts-plots"><i class="fa fa-check"></i><b>21.2</b> TS Plots</a></li>
<li class="chapter" data-level="21.3" data-path="arima-models.html"><a href="arima-models.html#box-cox-transformation"><i class="fa fa-check"></i><b>21.3</b> Box-Cox transformation</a></li>
<li class="chapter" data-level="21.4" data-path="arima-models.html"><a href="arima-models.html#stationarity"><i class="fa fa-check"></i><b>21.4</b> Stationarity</a></li>
<li class="chapter" data-level="21.5" data-path="arima-models.html"><a href="arima-models.html#modeling-arima"><i class="fa fa-check"></i><b>21.5</b> Modeling ARIMA</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="grid-search-for-arima.html"><a href="grid-search-for-arima.html"><i class="fa fa-check"></i><b>22</b> Grid search for ARIMA</a></li>
<li class="chapter" data-level="23" data-path="time-series-embedding.html"><a href="time-series-embedding.html"><i class="fa fa-check"></i><b>23</b> Time Series Embedding</a>
<ul>
<li class="chapter" data-level="23.1" data-path="time-series-embedding.html"><a href="time-series-embedding.html#var-for-recursive-forecasting"><i class="fa fa-check"></i><b>23.1</b> VAR for Recursive Forecasting</a></li>
<li class="chapter" data-level="23.2" data-path="time-series-embedding.html"><a href="time-series-embedding.html#embedding-for-direct-forecast"><i class="fa fa-check"></i><b>23.2</b> Embedding for Direct Forecast</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="random-forest-1.html"><a href="random-forest-1.html"><i class="fa fa-check"></i><b>24</b> Random Forest</a>
<ul>
<li class="chapter" data-level="24.1" data-path="random-forest-1.html"><a href="random-forest-1.html#univariate"><i class="fa fa-check"></i><b>24.1</b> Univariate</a></li>
<li class="chapter" data-level="24.2" data-path="random-forest-1.html"><a href="random-forest-1.html#multivariate"><i class="fa fa-check"></i><b>24.2</b> Multivariate</a></li>
<li class="chapter" data-level="24.3" data-path="random-forest-1.html"><a href="random-forest-1.html#rolling-and-expanding-windows"><i class="fa fa-check"></i><b>24.3</b> Rolling and expanding windows</a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="recurrent-neural-networks.html"><a href="recurrent-neural-networks.html"><i class="fa fa-check"></i><b>25</b> Recurrent Neural Networks</a>
<ul>
<li class="chapter" data-level="25.1" data-path="recurrent-neural-networks.html"><a href="recurrent-neural-networks.html#keras"><i class="fa fa-check"></i><b>25.1</b> Keras</a></li>
<li class="chapter" data-level="25.2" data-path="recurrent-neural-networks.html"><a href="recurrent-neural-networks.html#input-tensors"><i class="fa fa-check"></i><b>25.2</b> Input Tensors</a></li>
<li class="chapter" data-level="25.3" data-path="recurrent-neural-networks.html"><a href="recurrent-neural-networks.html#plain-rnn"><i class="fa fa-check"></i><b>25.3</b> Plain RNN</a></li>
<li class="chapter" data-level="25.4" data-path="recurrent-neural-networks.html"><a href="recurrent-neural-networks.html#lstm"><i class="fa fa-check"></i><b>25.4</b> LSTM</a></li>
</ul></li>
<li class="part"><span><b>VIII Dimension Reduction Methods</b></span></li>
<li class="chapter" data-level="" data-path="matrix-decompositions.html"><a href="matrix-decompositions.html"><i class="fa fa-check"></i>Matrix Decompositions</a></li>
<li class="chapter" data-level="26" data-path="eigenvectors-and-eigenvalues.html"><a href="eigenvectors-and-eigenvalues.html"><i class="fa fa-check"></i><b>26</b> Eigenvectors and eigenvalues</a></li>
<li class="chapter" data-level="27" data-path="singular-value-decomposition.html"><a href="singular-value-decomposition.html"><i class="fa fa-check"></i><b>27</b> Singular Value Decomposition</a></li>
<li class="chapter" data-level="28" data-path="rankr-approximations.html"><a href="rankr-approximations.html"><i class="fa fa-check"></i><b>28</b> Rank(r) Approximations</a></li>
<li class="chapter" data-level="29" data-path="moore-penrose-inverse.html"><a href="moore-penrose-inverse.html"><i class="fa fa-check"></i><b>29</b> Moore-Penrose inverse</a></li>
<li class="chapter" data-level="30" data-path="principle-component-analysis.html"><a href="principle-component-analysis.html"><i class="fa fa-check"></i><b>30</b> Principle Component Analysis</a></li>
<li class="chapter" data-level="31" data-path="factor-analysis.html"><a href="factor-analysis.html"><i class="fa fa-check"></i><b>31</b> Factor Analysis</a></li>
<li class="part"><span><b>IX Network Analysis</b></span></li>
<li class="chapter" data-level="" data-path="graphical-network-analysis.html"><a href="graphical-network-analysis.html"><i class="fa fa-check"></i>Graphical Network Analysis</a></li>
<li class="chapter" data-level="32" data-path="fundementals.html"><a href="fundementals.html"><i class="fa fa-check"></i><b>32</b> Fundementals</a>
<ul>
<li class="chapter" data-level="32.1" data-path="fundementals.html"><a href="fundementals.html#covariance"><i class="fa fa-check"></i><b>32.1</b> Covariance</a></li>
<li class="chapter" data-level="32.2" data-path="fundementals.html"><a href="fundementals.html#correlation"><i class="fa fa-check"></i><b>32.2</b> Correlation</a></li>
<li class="chapter" data-level="32.3" data-path="fundementals.html"><a href="fundementals.html#precision-matrix"><i class="fa fa-check"></i><b>32.3</b> Precision Matrix</a></li>
<li class="chapter" data-level="32.4" data-path="fundementals.html"><a href="fundementals.html#semi-partial-correlation"><i class="fa fa-check"></i><b>32.4</b> Semi-partial Correlation</a></li>
</ul></li>
<li class="chapter" data-level="33" data-path="regularized-covariance-matrix.html"><a href="regularized-covariance-matrix.html"><i class="fa fa-check"></i><b>33</b> Regularized Covariance Matrix</a>
<ul>
<li class="chapter" data-level="33.1" data-path="regularized-covariance-matrix.html"><a href="regularized-covariance-matrix.html#multivariate-gaussian-distribution"><i class="fa fa-check"></i><b>33.1</b> Multivariate Gaussian Distribution</a></li>
<li class="chapter" data-level="33.2" data-path="regularized-covariance-matrix.html"><a href="regularized-covariance-matrix.html#high-dimensional-data"><i class="fa fa-check"></i><b>33.2</b> High-dimensional data</a></li>
<li class="chapter" data-level="33.3" data-path="regularized-covariance-matrix.html"><a href="regularized-covariance-matrix.html#ridge-ell_2-and-glasso-ell_1"><i class="fa fa-check"></i><b>33.3</b> Ridge (<span class="math inline">\(\ell_{2}\)</span>) and glasso (<span class="math inline">\(\ell_{1}\)</span>)</a></li>
</ul></li>
<li class="part"><span><b>X Labs</b></span></li>
<li class="chapter" data-level="34" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html"><i class="fa fa-check"></i><b>34</b> R Lab 1 - Basics I</a>
<ul>
<li class="chapter" data-level="34.1" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html#r-rstudio-and-r-packages"><i class="fa fa-check"></i><b>34.1</b> R, RStudio, and R Packages</a></li>
<li class="chapter" data-level="34.2" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html#rstudio"><i class="fa fa-check"></i><b>34.2</b> RStudio</a></li>
<li class="chapter" data-level="34.3" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html#working-directory"><i class="fa fa-check"></i><b>34.3</b> Working directory</a></li>
<li class="chapter" data-level="34.4" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html#data-types-and-stuctures"><i class="fa fa-check"></i><b>34.4</b> Data Types and Stuctures</a></li>
<li class="chapter" data-level="34.5" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html#vectors"><i class="fa fa-check"></i><b>34.5</b> Vectors</a></li>
<li class="chapter" data-level="34.6" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html#subsetting-vectors"><i class="fa fa-check"></i><b>34.6</b> Subsetting Vectors</a></li>
<li class="chapter" data-level="34.7" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html#vectorization-or-vector-operations"><i class="fa fa-check"></i><b>34.7</b> Vectorization or vector operations</a></li>
<li class="chapter" data-level="34.8" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html#matrices"><i class="fa fa-check"></i><b>34.8</b> Matrices</a></li>
<li class="chapter" data-level="34.9" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html#matrix-operations"><i class="fa fa-check"></i><b>34.9</b> Matrix Operations</a></li>
<li class="chapter" data-level="34.10" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html#subsetting-matrix"><i class="fa fa-check"></i><b>34.10</b> Subsetting Matrix</a></li>
<li class="chapter" data-level="34.11" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html#r-style-guide"><i class="fa fa-check"></i><b>34.11</b> R-Style Guide</a></li>
</ul></li>
<li class="chapter" data-level="35" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html"><i class="fa fa-check"></i><b>35</b> R Lab 2 - Basics II</a>
<ul>
<li class="chapter" data-level="35.1" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#data-frames-and-lists"><i class="fa fa-check"></i><b>35.1</b> Data frames and lists</a>
<ul>
<li class="chapter" data-level="35.1.1" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#lists"><i class="fa fa-check"></i><b>35.1.1</b> Lists</a></li>
<li class="chapter" data-level="35.1.2" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#data-frames"><i class="fa fa-check"></i><b>35.1.2</b> Data Frames</a></li>
<li class="chapter" data-level="35.1.3" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#reading-importing-and-writting-exporting-data-files"><i class="fa fa-check"></i><b>35.1.3</b> Reading (importing) and writting (exporting) data files</a></li>
<li class="chapter" data-level="35.1.4" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#subsetting-data-frames"><i class="fa fa-check"></i><b>35.1.4</b> Subsetting Data Frames</a></li>
<li class="chapter" data-level="35.1.5" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#plotting-from-data-frame"><i class="fa fa-check"></i><b>35.1.5</b> Plotting from data frame</a></li>
<li class="chapter" data-level="35.1.6" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#some-useful-functions"><i class="fa fa-check"></i><b>35.1.6</b> Some useful functions</a></li>
<li class="chapter" data-level="35.1.7" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#categorical-variables-in-data-frames"><i class="fa fa-check"></i><b>35.1.7</b> Categorical Variables in Data Frames</a></li>
</ul></li>
<li class="chapter" data-level="35.2" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#programming-basics"><i class="fa fa-check"></i><b>35.2</b> Programming Basics</a>
<ul>
<li class="chapter" data-level="35.2.1" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#ifelse"><i class="fa fa-check"></i><b>35.2.1</b> if/Else</a></li>
<li class="chapter" data-level="35.2.2" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#loops"><i class="fa fa-check"></i><b>35.2.2</b> Loops</a></li>
<li class="chapter" data-level="35.2.3" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#the-apply-family"><i class="fa fa-check"></i><b>35.2.3</b> The <code>apply()</code> family</a></li>
<li class="chapter" data-level="35.2.4" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#functions"><i class="fa fa-check"></i><b>35.2.4</b> Functions</a></li>
<li class="chapter" data-level="35.2.5" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#dplyr"><i class="fa fa-check"></i><b>35.2.5</b> <code>dplyr()</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="36" data-path="r-lab-3---preparing-the-data.html"><a href="r-lab-3---preparing-the-data.html"><i class="fa fa-check"></i><b>36</b> R Lab 3 - Preparing the data</a>
<ul>
<li class="chapter" data-level="36.1" data-path="r-lab-3---preparing-the-data.html"><a href="r-lab-3---preparing-the-data.html#preparing-the-data-for-a-regression-analysis-with-lm"><i class="fa fa-check"></i><b>36.1</b> Preparing the data for a regression analysis with <code>lm()</code></a>
<ul>
<li class="chapter" data-level="36.1.1" data-path="r-lab-3---preparing-the-data.html"><a href="r-lab-3---preparing-the-data.html#factor-variables"><i class="fa fa-check"></i><b>36.1.1</b> Factor variables</a></li>
<li class="chapter" data-level="36.1.2" data-path="r-lab-3---preparing-the-data.html"><a href="r-lab-3---preparing-the-data.html#dummy-coding"><i class="fa fa-check"></i><b>36.1.2</b> Dummy Coding</a></li>
<li class="chapter" data-level="36.1.3" data-path="r-lab-3---preparing-the-data.html"><a href="r-lab-3---preparing-the-data.html#column-variable-names"><i class="fa fa-check"></i><b>36.1.3</b> Column (Variable) names</a></li>
<li class="chapter" data-level="36.1.4" data-path="r-lab-3---preparing-the-data.html"><a href="r-lab-3---preparing-the-data.html#data-subsetting-and-missing-values"><i class="fa fa-check"></i><b>36.1.4</b> Data subsetting and missing values</a></li>
</ul></li>
<li class="chapter" data-level="36.2" data-path="r-lab-3---preparing-the-data.html"><a href="r-lab-3---preparing-the-data.html#dummy-variable-models"><i class="fa fa-check"></i><b>36.2</b> “DUMMY” variable models</a>
<ul>
<li class="chapter" data-level="36.2.1" data-path="r-lab-3---preparing-the-data.html"><a href="r-lab-3---preparing-the-data.html#mtcars-example"><i class="fa fa-check"></i><b>36.2.1</b> <code>mtcars</code> example</a></li>
<li class="chapter" data-level="36.2.2" data-path="r-lab-3---preparing-the-data.html"><a href="r-lab-3---preparing-the-data.html#model.matrix"><i class="fa fa-check"></i><b>36.2.2</b> <code>model.matrix()</code></a></li>
<li class="chapter" data-level="36.2.3" data-path="r-lab-3---preparing-the-data.html"><a href="r-lab-3---preparing-the-data.html#example-with-a-bigger-data-set-autompg"><i class="fa fa-check"></i><b>36.2.3</b> Example with a bigger data set: <code>Autompg</code></a></li>
<li class="chapter" data-level="36.2.4" data-path="r-lab-3---preparing-the-data.html"><a href="r-lab-3---preparing-the-data.html#some-more-data-management-tools-for-subsetting-complete.cases-is.na-and-within"><i class="fa fa-check"></i><b>36.2.4</b> Some more data management tools for subsetting: <code>complete.cases()</code>, <code>is.na()</code>, and <code>within()</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="37" data-path="r-lab-4---simulation-in-r.html"><a href="r-lab-4---simulation-in-r.html"><i class="fa fa-check"></i><b>37</b> R Lab 4 - Simulation in R</a>
<ul>
<li class="chapter" data-level="37.1" data-path="r-lab-4---simulation-in-r.html"><a href="r-lab-4---simulation-in-r.html#sampling-in-r-sample"><i class="fa fa-check"></i><b>37.1</b> Sampling in R: <code>sample()</code></a></li>
<li class="chapter" data-level="37.2" data-path="r-lab-4---simulation-in-r.html"><a href="r-lab-4---simulation-in-r.html#random-number-generating-with-probablity-distributions"><i class="fa fa-check"></i><b>37.2</b> Random number generating with probablity distributions</a></li>
<li class="chapter" data-level="37.3" data-path="r-lab-4---simulation-in-r.html"><a href="r-lab-4---simulation-in-r.html#simulation-for-statistical-inference"><i class="fa fa-check"></i><b>37.3</b> Simulation for statistical inference</a></li>
<li class="chapter" data-level="37.4" data-path="r-lab-4---simulation-in-r.html"><a href="r-lab-4---simulation-in-r.html#creataing-data-with-a-data-generating-model-dgm"><i class="fa fa-check"></i><b>37.4</b> Creataing data with a Data Generating Model (DGM)</a></li>
<li class="chapter" data-level="37.5" data-path="r-lab-4---simulation-in-r.html"><a href="r-lab-4---simulation-in-r.html#bootstrapping"><i class="fa fa-check"></i><b>37.5</b> Bootstrapping</a></li>
<li class="chapter" data-level="37.6" data-path="r-lab-4---simulation-in-r.html"><a href="r-lab-4---simulation-in-r.html#monty-hall---fun-example"><i class="fa fa-check"></i><b>37.6</b> Monty Hall - Fun example</a></li>
</ul></li>
<li class="part"><span><b>XI Appendix</b></span></li>
<li class="chapter" data-level="38" data-path="algorithmic-optimization.html"><a href="algorithmic-optimization.html"><i class="fa fa-check"></i><b>38</b> Algorithmic Optimization</a>
<ul>
<li class="chapter" data-level="38.1" data-path="algorithmic-optimization.html"><a href="algorithmic-optimization.html#brute-force-optimization"><i class="fa fa-check"></i><b>38.1</b> Brute-force optimization</a></li>
<li class="chapter" data-level="38.2" data-path="algorithmic-optimization.html"><a href="algorithmic-optimization.html#derivative-based-methods"><i class="fa fa-check"></i><b>38.2</b> Derivative-based methods</a></li>
<li class="chapter" data-level="38.3" data-path="algorithmic-optimization.html"><a href="algorithmic-optimization.html#ml-estimation-with-logistic-regression"><i class="fa fa-check"></i><b>38.3</b> ML Estimation with logistic regression</a></li>
<li class="chapter" data-level="38.4" data-path="algorithmic-optimization.html"><a href="algorithmic-optimization.html#gradient-descent-algorithm"><i class="fa fa-check"></i><b>38.4</b> Gradient Descent Algorithm</a>
<ul>
<li class="chapter" data-level="38.4.1" data-path="algorithmic-optimization.html"><a href="algorithmic-optimization.html#one-variable"><i class="fa fa-check"></i><b>38.4.1</b> One-variable</a></li>
<li class="chapter" data-level="38.4.2" data-path="algorithmic-optimization.html"><a href="algorithmic-optimization.html#adjustable-lr-and-sgd"><i class="fa fa-check"></i><b>38.4.2</b> Adjustable <code>lr</code> and SGD</a></li>
<li class="chapter" data-level="38.4.3" data-path="algorithmic-optimization.html"><a href="algorithmic-optimization.html#multivariable"><i class="fa fa-check"></i><b>38.4.3</b> Multivariable</a></li>
</ul></li>
<li class="chapter" data-level="38.5" data-path="algorithmic-optimization.html"><a href="algorithmic-optimization.html#optimization-with-r"><i class="fa fa-check"></i><b>38.5</b> Optimization with R</a></li>
</ul></li>
<li class="chapter" data-level="39" data-path="imbalanced-data.html"><a href="imbalanced-data.html"><i class="fa fa-check"></i><b>39</b> Imbalanced Data</a>
<ul>
<li class="chapter" data-level="39.1" data-path="imbalanced-data.html"><a href="imbalanced-data.html#smote"><i class="fa fa-check"></i><b>39.1</b> <code>SMOTE</code></a></li>
<li class="chapter" data-level="39.2" data-path="imbalanced-data.html"><a href="imbalanced-data.html#fraud-detection"><i class="fa fa-check"></i><b>39.2</b> Fraud detection</a></li>
</ul></li>
<li class="chapter" data-level="40" data-path="footnotes-and-citations.html"><a href="footnotes-and-citations.html"><i class="fa fa-check"></i><b>40</b> Footnotes and citations</a>
<ul>
<li class="chapter" data-level="40.1" data-path="footnotes-and-citations.html"><a href="footnotes-and-citations.html#footnotes"><i class="fa fa-check"></i><b>40.1</b> Footnotes</a></li>
<li class="chapter" data-level="40.2" data-path="footnotes-and-citations.html"><a href="footnotes-and-citations.html#citations"><i class="fa fa-check"></i><b>40.2</b> Citations</a></li>
</ul></li>
<li class="chapter" data-level="41" data-path="blocks.html"><a href="blocks.html"><i class="fa fa-check"></i><b>41</b> Blocks</a>
<ul>
<li class="chapter" data-level="41.1" data-path="blocks.html"><a href="blocks.html#equations"><i class="fa fa-check"></i><b>41.1</b> Equations</a></li>
<li class="chapter" data-level="41.2" data-path="blocks.html"><a href="blocks.html#theorems-and-proofs"><i class="fa fa-check"></i><b>41.2</b> Theorems and proofs</a></li>
<li class="chapter" data-level="41.3" data-path="blocks.html"><a href="blocks.html#callout-blocks"><i class="fa fa-check"></i><b>41.3</b> Callout blocks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/yaydede/toolbox" target="blank"> 2023 Yigit Aydede - Bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Toolbox for Social Scientists and Policy Analysts</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ensemble-learning" class="section level1 hasAnchor" number="13">
<h1><span class="header-section-number">Chapter 13</span> Ensemble Learning<a href="ensemble-learning.html#ensemble-learning" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Bagging, random forests and, boosting methods are the main methods of ensemble learning - a machine learning method where multiple models are trained to solve the same problem. The main idea is that, instead of using all features (predictors) in one complex base model running on the whole data, we combine multiple models each using selected number of features and subsections of the data. With this, we can have a more robust learning system.</p>
<p>What inspires ensemble learning is the idea of the “wisdom of crowds”. It suggests that “many are smarter than the few” so that collective decision-making of a diverse and larger group of individuals is better than that of a single expert. When we use a single robust model, poor predictors would be eliminated in the training procedure. Although each poor predictor has a very small contribution in training, their combination would be significant. Ensemble learning systems help these poor predictors have their “voice” in the training process by <strong>keeping them in the system rather than eliminating them</strong>. That is the main reason why ensemble methods represent robust learning algorithms in machine learning.</p>
<div id="bagging" class="section level2 hasAnchor" number="13.1">
<h2><span class="header-section-number">13.1</span> Bagging<a href="ensemble-learning.html#bagging" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Bagging gets its name from <strong>B</strong>ootstrap <strong>agg</strong>regat<strong>ing</strong> of trees. The idea is simple: we train many trees each of which use a separate bootstrapped sample then aggregate them to one tree for the final decision. It works with few steps:</p>
<ol style="list-style-type: decimal">
<li>Select number of trees (B), and the tree depth (D),</li>
<li>Create a loop (B) times,</li>
<li>In each loop, (a) generate a bootstrap sample from the original data; (b) estimate a tree of depth D on that sample.</li>
</ol>
<p>Let’s see an example with the titanic dataset:</p>
<div class="sourceCode" id="cb587"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb587-1"><a href="ensemble-learning.html#cb587-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(PASWR)</span>
<span id="cb587-2"><a href="ensemble-learning.html#cb587-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart)</span>
<span id="cb587-3"><a href="ensemble-learning.html#cb587-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart.plot)</span>
<span id="cb587-4"><a href="ensemble-learning.html#cb587-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(titanic3)</span>
<span id="cb587-5"><a href="ensemble-learning.html#cb587-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb587-6"><a href="ensemble-learning.html#cb587-6" aria-hidden="true" tabindex="-1"></a><span class="co"># This is for a set of colors in each tree</span></span>
<span id="cb587-7"><a href="ensemble-learning.html#cb587-7" aria-hidden="true" tabindex="-1"></a>clr <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;pink&quot;</span>,<span class="st">&quot;red&quot;</span>,<span class="st">&quot;blue&quot;</span>,<span class="st">&quot;yellow&quot;</span>,<span class="st">&quot;darkgreen&quot;</span>,</span>
<span id="cb587-8"><a href="ensemble-learning.html#cb587-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">&quot;orange&quot;</span>,<span class="st">&quot;brown&quot;</span>,<span class="st">&quot;purple&quot;</span>,<span class="st">&quot;darkblue&quot;</span>)</span>
<span id="cb587-9"><a href="ensemble-learning.html#cb587-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb587-10"><a href="ensemble-learning.html#cb587-10" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">nrow</span>(titanic3)</span>
<span id="cb587-11"><a href="ensemble-learning.html#cb587-11" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">3</span>))</span>
<span id="cb587-12"><a href="ensemble-learning.html#cb587-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb587-13"><a href="ensemble-learning.html#cb587-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>){  <span class="co"># Here B = 9</span></span>
<span id="cb587-14"><a href="ensemble-learning.html#cb587-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set.seed</span>(i<span class="sc">*</span><span class="dv">2</span>)</span>
<span id="cb587-15"><a href="ensemble-learning.html#cb587-15" aria-hidden="true" tabindex="-1"></a>  idx <span class="ot">=</span> <span class="fu">sample</span>(n, n, <span class="at">replace =</span> <span class="cn">TRUE</span>) <span class="co">#Bootstrap sampling with replacement</span></span>
<span id="cb587-16"><a href="ensemble-learning.html#cb587-16" aria-hidden="true" tabindex="-1"></a>  tr <span class="ot">&lt;-</span> titanic3[idx,]</span>
<span id="cb587-17"><a href="ensemble-learning.html#cb587-17" aria-hidden="true" tabindex="-1"></a>  cart <span class="ot">=</span>  <span class="fu">rpart</span>(survived<span class="sc">~</span>sex<span class="sc">+</span>age<span class="sc">+</span>pclass<span class="sc">+</span>sibsp<span class="sc">+</span>parch,</span>
<span id="cb587-18"><a href="ensemble-learning.html#cb587-18" aria-hidden="true" tabindex="-1"></a>                <span class="at">cp =</span> <span class="dv">0</span>, <span class="at">data =</span> tr, <span class="at">method =</span> <span class="st">&quot;class&quot;</span>) <span class="co">#unpruned</span></span>
<span id="cb587-19"><a href="ensemble-learning.html#cb587-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prp</span>(cart, <span class="at">type=</span><span class="dv">1</span>, <span class="at">extra=</span><span class="dv">1</span>, <span class="at">box.col=</span>clr[i])</span>
<span id="cb587-20"><a href="ensemble-learning.html#cb587-20" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="12-Ensemble_files/figure-html/en1-1.png" width="672" /></p>
<p>What are we going to do with these 9 trees?</p>
<p>In regression trees, the prediction will be the <strong>average of the resulting predictions</strong>. In classification trees, we <strong>take a majority vote</strong>.</p>
<p>Since averaging a set of observations by bootstrapping reduces the variance, the prediction accuracy increases. More importantly, compared to CART, the results would be much less sensitive to the original sample. As a result, they show impressive improvement in accuracy.</p>
<p>Below, we have an algorithm that follows the steps for bagging in classification. Let’s start with a single tree and see how we can improve it with bagging:</p>
<div class="sourceCode" id="cb588"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb588-1"><a href="ensemble-learning.html#cb588-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ROCR)</span>
<span id="cb588-2"><a href="ensemble-learning.html#cb588-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb588-3"><a href="ensemble-learning.html#cb588-3" aria-hidden="true" tabindex="-1"></a><span class="co">#test/train split</span></span>
<span id="cb588-4"><a href="ensemble-learning.html#cb588-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb588-5"><a href="ensemble-learning.html#cb588-5" aria-hidden="true" tabindex="-1"></a>ind <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(titanic3), <span class="fu">nrow</span>(titanic3) <span class="sc">*</span> <span class="fl">0.8</span>)</span>
<span id="cb588-6"><a href="ensemble-learning.html#cb588-6" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> titanic3[ind, ]</span>
<span id="cb588-7"><a href="ensemble-learning.html#cb588-7" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> titanic3[<span class="sc">-</span>ind, ]</span>
<span id="cb588-8"><a href="ensemble-learning.html#cb588-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb588-9"><a href="ensemble-learning.html#cb588-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Single tree</span></span>
<span id="cb588-10"><a href="ensemble-learning.html#cb588-10" aria-hidden="true" tabindex="-1"></a>cart <span class="ot">&lt;-</span>  <span class="fu">rpart</span>(survived <span class="sc">~</span> sex <span class="sc">+</span> age <span class="sc">+</span> pclass <span class="sc">+</span> sibsp <span class="sc">+</span> parch,</span>
<span id="cb588-11"><a href="ensemble-learning.html#cb588-11" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">&quot;class&quot;</span>) <span class="co">#Pruned</span></span>
<span id="cb588-12"><a href="ensemble-learning.html#cb588-12" aria-hidden="true" tabindex="-1"></a>phat1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(cart, test, <span class="at">type =</span> <span class="st">&quot;prob&quot;</span>) </span>
<span id="cb588-13"><a href="ensemble-learning.html#cb588-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb588-14"><a href="ensemble-learning.html#cb588-14" aria-hidden="true" tabindex="-1"></a><span class="co">#AUC</span></span>
<span id="cb588-15"><a href="ensemble-learning.html#cb588-15" aria-hidden="true" tabindex="-1"></a>pred_rocr <span class="ot">&lt;-</span> <span class="fu">prediction</span>(phat1[,<span class="dv">2</span>], test<span class="sc">$</span>survived)</span>
<span id="cb588-16"><a href="ensemble-learning.html#cb588-16" aria-hidden="true" tabindex="-1"></a>auc_ROCR <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred_rocr, <span class="at">measure =</span> <span class="st">&quot;auc&quot;</span>)</span>
<span id="cb588-17"><a href="ensemble-learning.html#cb588-17" aria-hidden="true" tabindex="-1"></a>auc_ROCR<span class="sc">@</span>y.values[[<span class="dv">1</span>]]</span></code></pre></div>
<pre><code>## [1] 0.8352739</code></pre>
<p>Now, we apply bagging:</p>
<div class="sourceCode" id="cb590"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb590-1"><a href="ensemble-learning.html#cb590-1" aria-hidden="true" tabindex="-1"></a>B <span class="ot">=</span> <span class="dv">100</span> <span class="co"># number of trees</span></span>
<span id="cb590-2"><a href="ensemble-learning.html#cb590-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb590-3"><a href="ensemble-learning.html#cb590-3" aria-hidden="true" tabindex="-1"></a>phat2 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, B, <span class="fu">nrow</span>(test))</span>
<span id="cb590-4"><a href="ensemble-learning.html#cb590-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb590-5"><a href="ensemble-learning.html#cb590-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Loops</span></span>
<span id="cb590-6"><a href="ensemble-learning.html#cb590-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>B){  </span>
<span id="cb590-7"><a href="ensemble-learning.html#cb590-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set.seed</span>(i) <span class="co"># to make it reproducible</span></span>
<span id="cb590-8"><a href="ensemble-learning.html#cb590-8" aria-hidden="true" tabindex="-1"></a>  idx <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(train), <span class="fu">nrow</span>(train), <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb590-9"><a href="ensemble-learning.html#cb590-9" aria-hidden="true" tabindex="-1"></a>  dt <span class="ot">&lt;-</span> train[idx, ]</span>
<span id="cb590-10"><a href="ensemble-learning.html#cb590-10" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb590-11"><a href="ensemble-learning.html#cb590-11" aria-hidden="true" tabindex="-1"></a>  cart_B <span class="ot">&lt;-</span> <span class="fu">rpart</span>(survived <span class="sc">~</span> sex <span class="sc">+</span> age <span class="sc">+</span> pclass <span class="sc">+</span> sibsp <span class="sc">+</span> parch,</span>
<span id="cb590-12"><a href="ensemble-learning.html#cb590-12" aria-hidden="true" tabindex="-1"></a>                <span class="at">cp =</span> <span class="dv">0</span>, <span class="at">data =</span> dt, <span class="at">method =</span> <span class="st">&quot;class&quot;</span>) <span class="co"># unpruned</span></span>
<span id="cb590-13"><a href="ensemble-learning.html#cb590-13" aria-hidden="true" tabindex="-1"></a>  phat2[i,] <span class="ot">&lt;-</span> <span class="fu">predict</span>(cart_B, test, <span class="at">type =</span> <span class="st">&quot;prob&quot;</span>)[, <span class="dv">2</span>]</span>
<span id="cb590-14"><a href="ensemble-learning.html#cb590-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb590-15"><a href="ensemble-learning.html#cb590-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb590-16"><a href="ensemble-learning.html#cb590-16" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(phat2)</span></code></pre></div>
<pre><code>## [1] 100 262</code></pre>
<p>You can see in that <code>phat2</code> is a <span class="math inline">\(100 \times 262\)</span> matrix. Each column is representing the predicted probability that <code>survived</code> = 1. We have 100 trees (rows in <code>phat2</code>) and 100 predicted probabilities for each the observation in the test data. The only job we will have now to take the average of 100 predicted probabilities for each column.</p>
<div class="sourceCode" id="cb592"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb592-1"><a href="ensemble-learning.html#cb592-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Take the average</span></span>
<span id="cb592-2"><a href="ensemble-learning.html#cb592-2" aria-hidden="true" tabindex="-1"></a>phat_f <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(phat2)</span>
<span id="cb592-3"><a href="ensemble-learning.html#cb592-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb592-4"><a href="ensemble-learning.html#cb592-4" aria-hidden="true" tabindex="-1"></a><span class="co">#AUC</span></span>
<span id="cb592-5"><a href="ensemble-learning.html#cb592-5" aria-hidden="true" tabindex="-1"></a>pred_rocr <span class="ot">&lt;-</span> <span class="fu">prediction</span>(phat_f, test<span class="sc">$</span>survived)</span>
<span id="cb592-6"><a href="ensemble-learning.html#cb592-6" aria-hidden="true" tabindex="-1"></a>auc_ROCR <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred_rocr, <span class="at">measure =</span> <span class="st">&quot;auc&quot;</span>)</span>
<span id="cb592-7"><a href="ensemble-learning.html#cb592-7" aria-hidden="true" tabindex="-1"></a>auc_ROCR<span class="sc">@</span>y.values[[<span class="dv">1</span>]]</span></code></pre></div>
<pre><code>## [1] 0.8765668</code></pre>
<p>Hence, we have a slight improvement over a single tree. We can see how the number of trees (B) would cumulatively increases AUC (reduces MSPE in regressions).</p>
<div class="sourceCode" id="cb594"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb594-1"><a href="ensemble-learning.html#cb594-1" aria-hidden="true" tabindex="-1"></a>B <span class="ot">=</span> <span class="dv">300</span> </span>
<span id="cb594-2"><a href="ensemble-learning.html#cb594-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb594-3"><a href="ensemble-learning.html#cb594-3" aria-hidden="true" tabindex="-1"></a>phat3 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, B, <span class="fu">nrow</span>(test))</span>
<span id="cb594-4"><a href="ensemble-learning.html#cb594-4" aria-hidden="true" tabindex="-1"></a>AUC <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb594-5"><a href="ensemble-learning.html#cb594-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb594-6"><a href="ensemble-learning.html#cb594-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>B) {</span>
<span id="cb594-7"><a href="ensemble-learning.html#cb594-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set.seed</span>(i) </span>
<span id="cb594-8"><a href="ensemble-learning.html#cb594-8" aria-hidden="true" tabindex="-1"></a>  idx <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(train), <span class="fu">nrow</span>(train), <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb594-9"><a href="ensemble-learning.html#cb594-9" aria-hidden="true" tabindex="-1"></a>  dt <span class="ot">&lt;-</span> train[idx,]</span>
<span id="cb594-10"><a href="ensemble-learning.html#cb594-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb594-11"><a href="ensemble-learning.html#cb594-11" aria-hidden="true" tabindex="-1"></a>  fit <span class="ot">&lt;-</span> <span class="fu">rpart</span>(</span>
<span id="cb594-12"><a href="ensemble-learning.html#cb594-12" aria-hidden="true" tabindex="-1"></a>    survived <span class="sc">~</span> sex <span class="sc">+</span> age <span class="sc">+</span> pclass <span class="sc">+</span> sibsp <span class="sc">+</span> parch,</span>
<span id="cb594-13"><a href="ensemble-learning.html#cb594-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">cp =</span> <span class="dv">0</span>,</span>
<span id="cb594-14"><a href="ensemble-learning.html#cb594-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> dt,</span>
<span id="cb594-15"><a href="ensemble-learning.html#cb594-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">&quot;class&quot;</span></span>
<span id="cb594-16"><a href="ensemble-learning.html#cb594-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb594-17"><a href="ensemble-learning.html#cb594-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb594-18"><a href="ensemble-learning.html#cb594-18" aria-hidden="true" tabindex="-1"></a>  phat3[i, ] <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit, test, <span class="at">type =</span> <span class="st">&quot;prob&quot;</span>)[, <span class="dv">2</span>]</span>
<span id="cb594-19"><a href="ensemble-learning.html#cb594-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb594-20"><a href="ensemble-learning.html#cb594-20" aria-hidden="true" tabindex="-1"></a>  phat_f <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(phat3)</span>
<span id="cb594-21"><a href="ensemble-learning.html#cb594-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb594-22"><a href="ensemble-learning.html#cb594-22" aria-hidden="true" tabindex="-1"></a>  <span class="co">#AUC</span></span>
<span id="cb594-23"><a href="ensemble-learning.html#cb594-23" aria-hidden="true" tabindex="-1"></a>  pred_rocr <span class="ot">&lt;-</span> <span class="fu">prediction</span>(phat_f, test<span class="sc">$</span>survived)</span>
<span id="cb594-24"><a href="ensemble-learning.html#cb594-24" aria-hidden="true" tabindex="-1"></a>  auc_ROCR <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred_rocr, <span class="at">measure =</span> <span class="st">&quot;auc&quot;</span>)</span>
<span id="cb594-25"><a href="ensemble-learning.html#cb594-25" aria-hidden="true" tabindex="-1"></a>  AUC[i] <span class="ot">&lt;-</span> auc_ROCR<span class="sc">@</span>y.values[[<span class="dv">1</span>]]</span>
<span id="cb594-26"><a href="ensemble-learning.html#cb594-26" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb594-27"><a href="ensemble-learning.html#cb594-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb594-28"><a href="ensemble-learning.html#cb594-28" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(AUC, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb594-29"><a href="ensemble-learning.html#cb594-29" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;B - Number of trees&quot;</span>,</span>
<span id="cb594-30"><a href="ensemble-learning.html#cb594-30" aria-hidden="true" tabindex="-1"></a>     <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="12-Ensemble_files/figure-html/en5-1.png" width="672" /></p>
<p>As it is clear from the plot that, when we use a large value of B, the AUC (or error in regression) becomes stable. Therefore, we do not need to tune the number of trees with bagging. Using a value of B sufficiently large would suffice.</p>
<p>The main idea behind bagging is to reduce the variance in prediction. The reason for this reduction is simple: we take the mean prediction of all bootstrapped samples. Remember, when we use a simple tree and make 500 bootstrapping validations, each one of them gives a different MSPE (in regressions) or AUC (in classification). The difference now is that we average <code>yhat</code> in regressions or <code>phat</code> in classifications (or <code>yhat</code> with majority voting). This reduces the prediction uncertainty drastically.</p>
<p>Bagging works very well for high-variance base learners, such as decision trees or kNN. If the learner is stable, bagging adds little to the model’s performance. This brings us to another and improved ensemble method, random forests.</p>
</div>
<div id="random-forest" class="section level2 hasAnchor" number="13.2">
<h2><span class="header-section-number">13.2</span> Random Forest<a href="ensemble-learning.html#random-forest" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Random Forest = Bagging + subsample of covariates at each node</strong>. We have done the first part before. Random forests algorithm produces many single trees based on randomly selected a subset of observations and features. Since the algorithm leads to many single trees (like a forest) with a sufficient variation, the averaging them provides relatively a smooth and, more importantly, better predictive power than a single tree. Random forests and regression trees are particularly effective in settings with a large number of features that are correlated each other. The splits will generally ignore those covariates, and as a result, the performance will remain strong even in settings with many features.</p>
<p>We will use the Breiman and Cutler’s <a href="https://www.stat.berkeley.edu/~breiman/RandomForests/cc_home.htm">Random Forests for Classification and Regression</a>: <code>randomForest()</code><span class="citation">(<a href="#ref-Brei_2004" role="doc-biblioref"><strong>Brei_2004?</strong></a>)</span>.</p>
<p>Here are the steps and the loop structure:</p>
<ol style="list-style-type: decimal">
<li>Select number of trees (<code>ntree</code>), subsampling parameter (<code>mtry</code>), and the tree depth <code>maxnodes</code>,</li>
<li>Create a loop <code>ntree</code> times,</li>
<li>In each loop, (a) generate a bootstrap sample from the original data; (b) estimate a tree of depth <code>maxnodes</code> on that sample,</li>
<li>But, for each split in the tree (this is our second loop), randomly select <code>mtry</code> original covariates and do the split among those.</li>
</ol>
<p>Hence, bagging is a special case of random forest, with <code>mtry</code> = number of features (<span class="math inline">\(P\)</span>).</p>
<p>As we think on the idea of “subsampling covariates at each node” little bit more, we can see the rationale: suppose there is one very strong covariate in the sample. Almost all trees will use this covariate in the top split. All of the trees will look quite similar to each other. Hence the predictions will be highly correlated. <strong>Averaging many highly correlated quantities does not lead to a large reduction in variance</strong>. Random forests <strong>decorrelate</strong> the trees and, thus, further reduces the sensitivity of trees to the data points that are not in the original dataset.</p>
<p>How are we going to pick <code>mtry</code>? In practice, default values are <code>mtry</code> = <span class="math inline">\(P/3\)</span> in regression and <code>mtry</code> = <span class="math inline">\(\sqrt{P}\)</span> classification. (See <code>mtry</code> in <code>?randomForest</code>). Note that, with this parameter (<code>mtry</code>), we can run a pure bagging model with <code>randomForest()</code>, instead of <code>rpart()</code>, if we set <code>mtry</code> = <span class="math inline">\(P\)</span>.</p>
<p>With the bootstrap resampling process for each tree, random forests have an efficient and reasonable approximation of the test error calculated from out-of-bag (OOB) sets. When bootstrap aggregating is performed, two independent sets are created. One set, the bootstrap sample, is the data chosen to be “in-the-bag” by sampling with replacement. The out-of-bag set is all data not chosen in the sampling process. Hence, there is no need for cross-validation or a separate test set to obtain an unbiased estimate of the prediction error. It is estimated internally as each tree is constructed using a different bootstrap sample from the original data. About one-third of the cases (observations) are left out of the bootstrap sample and not used in the construction of the <span class="math inline">\(k^{th}\)</span> tree. In this way, a test set classification is obtained for each case in about one-third of the trees. In each run, the class is selected when it
gets most of the votes among the OOB cases. The proportion of times that the selected class for the observation is not equal to the true class over all observations in OOB set is called the OOB error estimate. This has proven to be unbiased in many tests. Note that the forest’s variance decreases as the number of trees grows. Thus, more accurate predictions are likely to be obtained by choosing a large number of trees.</p>
<p>You can think of a random forest model as a robust version of CART models. There are some default parameters that can be tuned in <code>randomForest()</code>. It is argued that, however, the problem of overfitting is minor in random forests.</p>
<blockquote>
<p>Segal (2004) demonstrates small gains in performance by controlling the depths of the individual trees grown in random forests. Our experience is that using full-grown trees seldom costs much, and results in one less tuning parameter. Figure 15.8 shows the modest effect of depth control in a simple regression example. (Hastie et al., 2009, p.596)</p>
</blockquote>
<p>Let’s start with a simulation to show random forest and CART models:</p>
<div class="sourceCode" id="cb595"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb595-1"><a href="ensemble-learning.html#cb595-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(randomForest)</span>
<span id="cb595-2"><a href="ensemble-learning.html#cb595-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Note that this is actually Bagging since we have only 1 variable</span></span>
<span id="cb595-3"><a href="ensemble-learning.html#cb595-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb595-4"><a href="ensemble-learning.html#cb595-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Our simulated data</span></span>
<span id="cb595-5"><a href="ensemble-learning.html#cb595-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb595-6"><a href="ensemble-learning.html#cb595-6" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">500</span></span>
<span id="cb595-7"><a href="ensemble-learning.html#cb595-7" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">runif</span>(n)</span>
<span id="cb595-8"><a href="ensemble-learning.html#cb595-8" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">sin</span>(<span class="dv">12</span> <span class="sc">*</span> (x <span class="sc">+</span> .<span class="dv">2</span>)) <span class="sc">/</span> (x <span class="sc">+</span> .<span class="dv">2</span>) <span class="sc">+</span> <span class="fu">rnorm</span>(n) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb595-9"><a href="ensemble-learning.html#cb595-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb595-10"><a href="ensemble-learning.html#cb595-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Fitting the models</span></span>
<span id="cb595-11"><a href="ensemble-learning.html#cb595-11" aria-hidden="true" tabindex="-1"></a>fit.tree <span class="ot">&lt;-</span> <span class="fu">rpart</span>(y <span class="sc">~</span> x) <span class="co">#CART</span></span>
<span id="cb595-12"><a href="ensemble-learning.html#cb595-12" aria-hidden="true" tabindex="-1"></a>fit.rf1 <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(y <span class="sc">~</span> x) <span class="co">#No depth control</span></span>
<span id="cb595-13"><a href="ensemble-learning.html#cb595-13" aria-hidden="true" tabindex="-1"></a>fit.rf2 <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(y <span class="sc">~</span> x, <span class="at">maxnodes =</span> <span class="dv">20</span>) <span class="co"># Control it</span></span>
<span id="cb595-14"><a href="ensemble-learning.html#cb595-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb595-15"><a href="ensemble-learning.html#cb595-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot observations and predicted values</span></span>
<span id="cb595-16"><a href="ensemble-learning.html#cb595-16" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(x), <span class="fu">max</span>(x), <span class="at">length.out =</span> <span class="dv">1000</span>)</span>
<span id="cb595-17"><a href="ensemble-learning.html#cb595-17" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb595-18"><a href="ensemble-learning.html#cb595-18" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x, y, <span class="at">col =</span> <span class="st">&quot;gray&quot;</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>))</span>
<span id="cb595-19"><a href="ensemble-learning.html#cb595-19" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(z,</span>
<span id="cb595-20"><a href="ensemble-learning.html#cb595-20" aria-hidden="true" tabindex="-1"></a>      <span class="fu">predict</span>(fit.rf1, <span class="fu">data.frame</span>(<span class="at">x =</span> z)),</span>
<span id="cb595-21"><a href="ensemble-learning.html#cb595-21" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;green&quot;</span>,</span>
<span id="cb595-22"><a href="ensemble-learning.html#cb595-22" aria-hidden="true" tabindex="-1"></a>      <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb595-23"><a href="ensemble-learning.html#cb595-23" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(z,</span>
<span id="cb595-24"><a href="ensemble-learning.html#cb595-24" aria-hidden="true" tabindex="-1"></a>      <span class="fu">predict</span>(fit.rf2, <span class="fu">data.frame</span>(<span class="at">x =</span> z)),</span>
<span id="cb595-25"><a href="ensemble-learning.html#cb595-25" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb595-26"><a href="ensemble-learning.html#cb595-26" aria-hidden="true" tabindex="-1"></a>      <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb595-27"><a href="ensemble-learning.html#cb595-27" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(z,</span>
<span id="cb595-28"><a href="ensemble-learning.html#cb595-28" aria-hidden="true" tabindex="-1"></a>      <span class="fu">predict</span>(fit.tree, <span class="fu">data.frame</span>(<span class="at">x =</span> z)),</span>
<span id="cb595-29"><a href="ensemble-learning.html#cb595-29" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>,</span>
<span id="cb595-30"><a href="ensemble-learning.html#cb595-30" aria-hidden="true" tabindex="-1"></a>      <span class="at">lwd =</span> <span class="fl">1.5</span>)</span>
<span id="cb595-31"><a href="ensemble-learning.html#cb595-31" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;bottomright&quot;</span>,</span>
<span id="cb595-32"><a href="ensemble-learning.html#cb595-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;Random Forest: maxnodes=max&quot;</span>,</span>
<span id="cb595-33"><a href="ensemble-learning.html#cb595-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;Random Forest: maxnodes=20&quot;</span>,</span>
<span id="cb595-34"><a href="ensemble-learning.html#cb595-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;CART: single regression tree&quot;</span>),</span>
<span id="cb595-35"><a href="ensemble-learning.html#cb595-35" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;green&quot;</span>, <span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>),</span>
<span id="cb595-36"><a href="ensemble-learning.html#cb595-36" aria-hidden="true" tabindex="-1"></a>  <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb595-37"><a href="ensemble-learning.html#cb595-37" aria-hidden="true" tabindex="-1"></a>  <span class="at">bty =</span> <span class="st">&quot;n&quot;</span></span>
<span id="cb595-38"><a href="ensemble-learning.html#cb595-38" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="12-Ensemble_files/figure-html/en6-1.png" width="672" /></p>
<p>The random forest models are definitely improvements over CART, but which one is better? Although random forest models should not overfit when increasing the number of trees (<code>ntree</code>) in the forest, in practice <code>maxnodes</code> and <code>mtry</code> are used as hyperparameters in the field.</p>
<p>Let’s use out-of-bag (OOB) MSE to tune Random Forest parameters in our case to see if there is any improvement.</p>
<div class="sourceCode" id="cb596"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb596-1"><a href="ensemble-learning.html#cb596-1" aria-hidden="true" tabindex="-1"></a>maxnode <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">500</span>)</span>
<span id="cb596-2"><a href="ensemble-learning.html#cb596-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(maxnode)) {</span>
<span id="cb596-3"><a href="ensemble-learning.html#cb596-3" aria-hidden="true" tabindex="-1"></a>  a <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(y <span class="sc">~</span> x, <span class="at">maxnodes =</span> maxnode[i])</span>
<span id="cb596-4"><a href="ensemble-learning.html#cb596-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">c</span>(maxnode[i], a<span class="sc">$</span>mse[<span class="dv">500</span>]))</span>
<span id="cb596-5"><a href="ensemble-learning.html#cb596-5" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] 10.0000000  0.3878058
## [1] 50.000000  0.335875
## [1] 100.0000000   0.3592119
## [1] 500.0000000   0.3905135</code></pre>
<div class="sourceCode" id="cb598"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb598-1"><a href="ensemble-learning.html#cb598-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Increase ntree = 1500</span></span>
<span id="cb598-2"><a href="ensemble-learning.html#cb598-2" aria-hidden="true" tabindex="-1"></a>maxnode <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">500</span>)</span>
<span id="cb598-3"><a href="ensemble-learning.html#cb598-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(maxnode)) {</span>
<span id="cb598-4"><a href="ensemble-learning.html#cb598-4" aria-hidden="true" tabindex="-1"></a>  a <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(y <span class="sc">~</span> x, <span class="at">maxnodes =</span> maxnode[i], <span class="at">ntree =</span> <span class="dv">2500</span>)</span>
<span id="cb598-5"><a href="ensemble-learning.html#cb598-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">c</span>(maxnode[i], a<span class="sc">$</span>mse[<span class="dv">500</span>]))</span>
<span id="cb598-6"><a href="ensemble-learning.html#cb598-6" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] 10.000000  0.391755
## [1] 50.0000000  0.3353198
## [1] 100.0000000   0.3616621
## [1] 500.0000000   0.3900982</code></pre>
<p>We can see that OOB-MSE is smaller with <code>maxnodes</code> = 50 even when we increase <code>ntree</code> = 1500 . Of course we can have a finer sequence of <code>maxnodes</code> series to test. Similarly, we can select parameter <code>mtry</code> with a grid search. In a bagged model we set <code>mtry</code> = <span class="math inline">\(P\)</span>. If we don’t set it, the default values for <code>mtry</code> are square-root of <span class="math inline">\(p\)</span> for classification and <span class="math inline">\(p/3\)</span> in regression, where <span class="math inline">\(p\)</span> is number of features. If we want, we can tune both parameters with cross-validation. The effectiveness of tuning random forest models in improving their prediction accuracy is an open question in practice.</p>
<p>Bagging and random forest models tend to work well for problems where there are important nonlinearities and interactions. More importantly, <strong>they are robust to the original sample</strong> and more efficient than single trees. However, <strong>the results would be less intuitive and difficult to interpret</strong>. Nevertheless, we can obtain an overall summary of the importance of each covariates using SSR (for regression) or Gini index (for classification). The index records the total amount that the SSR or Gini is decreased due to splits over a given covariate, averaged over all <code>ntree</code> trees.</p>
<div class="sourceCode" id="cb600"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb600-1"><a href="ensemble-learning.html#cb600-1" aria-hidden="true" tabindex="-1"></a>rf <span class="ot">&lt;-</span></span>
<span id="cb600-2"><a href="ensemble-learning.html#cb600-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">randomForest</span>(</span>
<span id="cb600-3"><a href="ensemble-learning.html#cb600-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as.factor</span>(survived) <span class="sc">~</span> sex <span class="sc">+</span> age <span class="sc">+</span> pclass <span class="sc">+</span> sibsp <span class="sc">+</span> parch,</span>
<span id="cb600-4"><a href="ensemble-learning.html#cb600-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> titanic3,</span>
<span id="cb600-5"><a href="ensemble-learning.html#cb600-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.action =</span> na.omit,</span>
<span id="cb600-6"><a href="ensemble-learning.html#cb600-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">localImp =</span> <span class="cn">TRUE</span>,</span>
<span id="cb600-7"><a href="ensemble-learning.html#cb600-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb600-8"><a href="ensemble-learning.html#cb600-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb600-9"><a href="ensemble-learning.html#cb600-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rf, <span class="at">main =</span> <span class="st">&quot;Learning curve of the forest&quot;</span>)</span>
<span id="cb600-10"><a href="ensemble-learning.html#cb600-10" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(</span>
<span id="cb600-11"><a href="ensemble-learning.html#cb600-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">&quot;topright&quot;</span>,</span>
<span id="cb600-12"><a href="ensemble-learning.html#cb600-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(</span>
<span id="cb600-13"><a href="ensemble-learning.html#cb600-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;Error for &#39;Survived&#39;&quot;</span>,</span>
<span id="cb600-14"><a href="ensemble-learning.html#cb600-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;Misclassification error&quot;</span>,</span>
<span id="cb600-15"><a href="ensemble-learning.html#cb600-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;Error for &#39;Dead&#39;&quot;</span></span>
<span id="cb600-16"><a href="ensemble-learning.html#cb600-16" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb600-17"><a href="ensemble-learning.html#cb600-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb600-18"><a href="ensemble-learning.html#cb600-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;green&quot;</span>, <span class="st">&quot;black&quot;</span>, <span class="st">&quot;red&quot;</span>)</span>
<span id="cb600-19"><a href="ensemble-learning.html#cb600-19" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="12-Ensemble_files/figure-html/en8-1.png" width="672" /></p>
<p>The plot shows the evolution of out-of-bag errors when the number of trees increases. The learning curves reach to a stable section right after a couple of trees. With 500 trees, which is the default number, the OOB estimate of our error rate is around 0.2, which can be seen in the basic information concerning our model below</p>
<div class="sourceCode" id="cb601"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb601-1"><a href="ensemble-learning.html#cb601-1" aria-hidden="true" tabindex="-1"></a>rf</span></code></pre></div>
<pre><code>## 
## Call:
##  randomForest(formula = as.factor(survived) ~ sex + age + pclass +      sibsp + parch, data = titanic3, localImp = TRUE, , na.action = na.omit) 
##                Type of random forest: classification
##                      Number of trees: 500
## No. of variables tried at each split: 2
## 
##         OOB estimate of  error rate: 19.69%
## Confusion matrix:
##     0   1 class.error
## 0 562  57  0.09208401
## 1 149 278  0.34894614</code></pre>
<p>We will see a several applications on CART, bagging and Random Forest later in Chapter 14.</p>
</div>
<div id="boosting" class="section level2 hasAnchor" number="13.3">
<h2><span class="header-section-number">13.3</span> Boosting<a href="ensemble-learning.html#boosting" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Boosting is an ensemble method that combines a set of “weak learners” into a strong learner to improve the prediction accuracy in self-learning algorithms. In boosting, the constructed iteration selects a random sample of data, fits a model, and then train sequentially. In each sequential model, the algorithm learns from the weaknesses of its predecessor (predictions errors) and tries to compensate for the weaknesses by “boosting” the weak rules from each individual classifier. The first original boosted application was offered in 1990 by Robert Schapire (1990) <span class="citation">(<a href="#ref-Schapire" role="doc-biblioref"><strong>Schapire?</strong></a>)</span>.<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a></p>
<p>Today, there are many boosting algorithms that are mainly grouped in the following three types:</p>
<ul>
<li>Gradient descent algorithm,</li>
<li>AdaBoost algorithm,</li>
<li>Xtreme gradient descent algorithm,</li>
</ul>
<p>We will start with a general application to show the idea behind the algorithm using the package <code>gbm</code>, <a href="https://cran.r-project.org/web/packages/gbm/gbm.pdf">Generalized Boosted Regression Models</a></p>
<div id="sequential-ensemble-with-gbm" class="section level3 hasAnchor" number="13.3.1">
<h3><span class="header-section-number">13.3.1</span> Sequential ensemble with <code>gbm</code><a href="ensemble-learning.html#sequential-ensemble-with-gbm" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Similar to bagging, boosting also combines a large number of decision trees. However, the trees are grown <strong>sequentially</strong> without bootstrap sampling. Instead each tree is fit on a modified version of the original dataset, the <strong>error</strong>.</p>
<p>In regression trees, for example, each tree is fit to the residuals from the previous tree model so that each iteration is focused on <strong>improving previous errors</strong>. This process would be very weird for an econometrician. The accepted model building practice in econometrics is that you should have a model that the errors (residuals) should be orthogonal (independent from) to covariates. Here, what we suggest is the opposite of this practice: start with a very low-depth (shallow) model that omits many relevant variables, run a linear regression, get the residuals (prediction errors), and run another regression that explains the residuals with covariates. This is called <strong>learning from mistakes</strong>.</p>
<p>Since there is no bootstrapping, this process is open to overfitting problem as it aims to minimize the in-sample prediction error. Hence, we introduce a <strong>hyperparameter</strong> that we can tune the learning process with cross-validation to stop the overfitting and get the best predictive model.</p>
<p>This hyperparameter (shrinkage parameter, also known as the <strong>learning rate</strong> or <strong>step-size reduction</strong>) limits the size of the errors.</p>
<p>Let’s see the whole process in a simple example inspired by <a href="https://freakonometrics.hypotheses.org/52782">Freakonometrics</a> <span class="citation">(<a href="#ref-Hyp_2018" role="doc-biblioref"><strong>Hyp_2018?</strong></a>)</span>:</p>
<div class="sourceCode" id="cb603"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb603-1"><a href="ensemble-learning.html#cb603-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First we will simulate our data</span></span>
<span id="cb603-2"><a href="ensemble-learning.html#cb603-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">300</span></span>
<span id="cb603-3"><a href="ensemble-learning.html#cb603-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb603-4"><a href="ensemble-learning.html#cb603-4" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">runif</span>(n) <span class="sc">*</span> <span class="dv">2</span> <span class="sc">*</span> pi)</span>
<span id="cb603-5"><a href="ensemble-learning.html#cb603-5" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">sin</span>(x) <span class="sc">+</span> <span class="fu">rnorm</span>(n) <span class="sc">/</span> <span class="dv">4</span></span>
<span id="cb603-6"><a href="ensemble-learning.html#cb603-6" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="st">&quot;x&quot;</span> <span class="ot">=</span> x, <span class="st">&quot;y&quot;</span> <span class="ot">=</span> y)</span>
<span id="cb603-7"><a href="ensemble-learning.html#cb603-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df<span class="sc">$</span>x, df<span class="sc">$</span>y, <span class="at">ylab =</span> <span class="st">&quot;y&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;x&quot;</span>, <span class="at">col =</span> <span class="st">&quot;grey&quot;</span>)</span></code></pre></div>
<p><img src="12-Ensemble_files/figure-html/en10-1.png" width="672" /></p>
<p>We will “boost” a single regression tree:</p>
<p><strong>Step 1</strong>: Fit the model by using in-sample data</p>
<div class="sourceCode" id="cb604"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb604-1"><a href="ensemble-learning.html#cb604-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression tree with rpart()</span></span>
<span id="cb604-2"><a href="ensemble-learning.html#cb604-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">rpart</span>(y <span class="sc">~</span> x, <span class="at">data =</span> df) <span class="co"># First fit: y~x</span></span>
<span id="cb604-3"><a href="ensemble-learning.html#cb604-3" aria-hidden="true" tabindex="-1"></a>yp <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit) <span class="co"># using in-sample data</span></span>
<span id="cb604-4"><a href="ensemble-learning.html#cb604-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb604-5"><a href="ensemble-learning.html#cb604-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot for single regression tree</span></span>
<span id="cb604-6"><a href="ensemble-learning.html#cb604-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df<span class="sc">$</span>x, df<span class="sc">$</span>y, <span class="at">ylab =</span> <span class="st">&quot;y&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;x&quot;</span>, <span class="at">col =</span> <span class="st">&quot;grey&quot;</span>)</span>
<span id="cb604-7"><a href="ensemble-learning.html#cb604-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(df<span class="sc">$</span>x, yp, <span class="at">type =</span> <span class="st">&quot;s&quot;</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span></code></pre></div>
<p><img src="12-Ensemble_files/figure-html/en11-1.png" width="672" /></p>
<p>Now, we will have a loop that will “boost” the model. What we mean by boosting is that we seek to improve <code>yhat</code>, i.e. <span class="math inline">\(\hat{f}(x_i)\)</span>, in areas where it does not perform well by fitting trees to the residuals.</p>
<p><strong>Step 2</strong>: Find the “error” and introduce a hyperparameter <code>h</code>.</p>
<div class="sourceCode" id="cb605"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb605-1"><a href="ensemble-learning.html#cb605-1" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="fl">0.1</span> <span class="co"># shrinkage parameter</span></span>
<span id="cb605-2"><a href="ensemble-learning.html#cb605-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb605-3"><a href="ensemble-learning.html#cb605-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the prediction error adjusted by h</span></span>
<span id="cb605-4"><a href="ensemble-learning.html#cb605-4" aria-hidden="true" tabindex="-1"></a>yr <span class="ot">&lt;-</span> df<span class="sc">$</span>y <span class="sc">-</span> h <span class="sc">*</span> yp </span>
<span id="cb605-5"><a href="ensemble-learning.html#cb605-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb605-6"><a href="ensemble-learning.html#cb605-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Add this adjusted prediction error, `yr` to our main data frame,</span></span>
<span id="cb605-7"><a href="ensemble-learning.html#cb605-7" aria-hidden="true" tabindex="-1"></a><span class="co"># which will be our target variable to predict later</span></span>
<span id="cb605-8"><a href="ensemble-learning.html#cb605-8" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>yr <span class="ot">&lt;-</span> yr</span>
<span id="cb605-9"><a href="ensemble-learning.html#cb605-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb605-10"><a href="ensemble-learning.html#cb605-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Store the &quot;first&quot; predictions in YP</span></span>
<span id="cb605-11"><a href="ensemble-learning.html#cb605-11" aria-hidden="true" tabindex="-1"></a>YP <span class="ot">&lt;-</span> h <span class="sc">*</span> yp </span></code></pre></div>
<p>Note that if <code>h</code>= 1, it would give us usual “residuals”. Hence, <code>h</code> controls for “how much error” we would like to reduce.</p>
<p><strong>Step 3</strong>: Now, we will predict the “error” in a loop that repeats itself many times.</p>
<div class="sourceCode" id="cb606"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb606-1"><a href="ensemble-learning.html#cb606-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Boosting loop for t times (trees)</span></span>
<span id="cb606-2"><a href="ensemble-learning.html#cb606-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (t <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>) {</span>
<span id="cb606-3"><a href="ensemble-learning.html#cb606-3" aria-hidden="true" tabindex="-1"></a>  fit <span class="ot">&lt;-</span> <span class="fu">rpart</span>(yr <span class="sc">~</span> x, <span class="at">data =</span> df) <span class="co"># here it&#39;s yr~x.</span></span>
<span id="cb606-4"><a href="ensemble-learning.html#cb606-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># We try to understand the prediction error by x&#39;s</span></span>
<span id="cb606-5"><a href="ensemble-learning.html#cb606-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb606-6"><a href="ensemble-learning.html#cb606-6" aria-hidden="true" tabindex="-1"></a>  yp <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit, <span class="at">newdata =</span> df)</span>
<span id="cb606-7"><a href="ensemble-learning.html#cb606-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb606-8"><a href="ensemble-learning.html#cb606-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># This is your main prediction added to YP</span></span>
<span id="cb606-9"><a href="ensemble-learning.html#cb606-9" aria-hidden="true" tabindex="-1"></a>  YP <span class="ot">&lt;-</span> <span class="fu">cbind</span>(YP, h <span class="sc">*</span> yp) </span>
<span id="cb606-10"><a href="ensemble-learning.html#cb606-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb606-11"><a href="ensemble-learning.html#cb606-11" aria-hidden="true" tabindex="-1"></a>  df<span class="sc">$</span>yr <span class="ot">&lt;-</span> df<span class="sc">$</span>yr <span class="sc">-</span> h <span class="sc">*</span> yp <span class="co"># errors for the next iteration</span></span>
<span id="cb606-12"><a href="ensemble-learning.html#cb606-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># i.e. the next target to predict!</span></span>
<span id="cb606-13"><a href="ensemble-learning.html#cb606-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb606-14"><a href="ensemble-learning.html#cb606-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb606-15"><a href="ensemble-learning.html#cb606-15" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(YP)</span></code></pre></div>
<pre><code>##  num [1:300, 1:101] 0.00966 0.00966 0.00966 0.00966 0.00966 ...
##  - attr(*, &quot;dimnames&quot;)=List of 2
##   ..$ : chr [1:300] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; ...
##   ..$ : chr [1:101] &quot;YP&quot; &quot;&quot; &quot;&quot; &quot;&quot; ...</code></pre>
<p>Look at <code>YP</code> now. We have a matrix 300 by 101. This is a matrix of <strong>predicted errors</strong>, except for the first column. So what?</p>
<div class="sourceCode" id="cb608"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb608-1"><a href="ensemble-learning.html#cb608-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to plot a single tree and boosted trees for different t</span></span>
<span id="cb608-2"><a href="ensemble-learning.html#cb608-2" aria-hidden="true" tabindex="-1"></a>viz <span class="ot">&lt;-</span> <span class="cf">function</span>(M) {</span>
<span id="cb608-3"><a href="ensemble-learning.html#cb608-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Boosting</span></span>
<span id="cb608-4"><a href="ensemble-learning.html#cb608-4" aria-hidden="true" tabindex="-1"></a>  yhat <span class="ot">&lt;-</span> <span class="fu">apply</span>(YP[, <span class="dv">1</span><span class="sc">:</span>M], <span class="dv">1</span>, sum) <span class="co"># This is predicted y for depth M</span></span>
<span id="cb608-5"><a href="ensemble-learning.html#cb608-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(df<span class="sc">$</span>x, df<span class="sc">$</span>y, <span class="at">ylab =</span> <span class="st">&quot;&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;&quot;</span>) <span class="co"># Data points</span></span>
<span id="cb608-6"><a href="ensemble-learning.html#cb608-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lines</span>(df<span class="sc">$</span>x, yhat, <span class="at">type =</span> <span class="st">&quot;s&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>) <span class="co"># line for boosting</span></span>
<span id="cb608-7"><a href="ensemble-learning.html#cb608-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb608-8"><a href="ensemble-learning.html#cb608-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Single Tree</span></span>
<span id="cb608-9"><a href="ensemble-learning.html#cb608-9" aria-hidden="true" tabindex="-1"></a>  fit <span class="ot">&lt;-</span> <span class="fu">rpart</span>(y <span class="sc">~</span> x, <span class="at">data =</span> df) <span class="co"># Single regression tree</span></span>
<span id="cb608-10"><a href="ensemble-learning.html#cb608-10" aria-hidden="true" tabindex="-1"></a>  yp <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit, <span class="at">newdata =</span> df) <span class="co"># prediction for the single tree</span></span>
<span id="cb608-11"><a href="ensemble-learning.html#cb608-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lines</span>(df<span class="sc">$</span>x, yp, <span class="at">type =</span> <span class="st">&quot;s&quot;</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>) <span class="co"># line for single tree</span></span>
<span id="cb608-12"><a href="ensemble-learning.html#cb608-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lines</span>(df<span class="sc">$</span>x, <span class="fu">sin</span>(df<span class="sc">$</span>x), <span class="at">lty =</span> <span class="dv">1</span>, <span class="at">col =</span> <span class="st">&quot;black&quot;</span>) <span class="co"># Line for DGM</span></span>
<span id="cb608-13"><a href="ensemble-learning.html#cb608-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb608-14"><a href="ensemble-learning.html#cb608-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb608-15"><a href="ensemble-learning.html#cb608-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Run each</span></span>
<span id="cb608-16"><a href="ensemble-learning.html#cb608-16" aria-hidden="true" tabindex="-1"></a><span class="fu">viz</span>(<span class="dv">5</span>)</span></code></pre></div>
<p><img src="12-Ensemble_files/figure-html/en14-1.png" width="672" /></p>
<div class="sourceCode" id="cb609"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb609-1"><a href="ensemble-learning.html#cb609-1" aria-hidden="true" tabindex="-1"></a><span class="fu">viz</span>(<span class="dv">101</span>)</span></code></pre></div>
<p><img src="12-Ensemble_files/figure-html/en14-2.png" width="672" /></p>
<p>Each of 100 trees is given in the <code>YP</code> matrix. <strong>Boosting combines the outputs of many “weak” learners (each tree) to produce a powerful “committee”.</strong> What if we change the shrinkage parameter? Let’s increase it to 1.8.</p>
<div class="sourceCode" id="cb610"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb610-1"><a href="ensemble-learning.html#cb610-1" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="fl">1.8</span> <span class="co"># shrinkage parameter </span></span>
<span id="cb610-2"><a href="ensemble-learning.html#cb610-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>yr <span class="ot">&lt;-</span> df<span class="sc">$</span>y <span class="sc">-</span> h<span class="sc">*</span>yp <span class="co"># Prediction errors with &quot;h&quot; after rpart</span></span>
<span id="cb610-3"><a href="ensemble-learning.html#cb610-3" aria-hidden="true" tabindex="-1"></a>YP <span class="ot">&lt;-</span> h<span class="sc">*</span>yp  <span class="co">#Store the &quot;first&quot; prediction errors in YP</span></span>
<span id="cb610-4"><a href="ensemble-learning.html#cb610-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb610-5"><a href="ensemble-learning.html#cb610-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Boosting Loop for t (number of trees) times</span></span>
<span id="cb610-6"><a href="ensemble-learning.html#cb610-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(t <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>){</span>
<span id="cb610-7"><a href="ensemble-learning.html#cb610-7" aria-hidden="true" tabindex="-1"></a>  fit <span class="ot">&lt;-</span> <span class="fu">rpart</span>(yr<span class="sc">~</span>x, <span class="at">data=</span>df) <span class="co"># here it&#39;s yr~x.  </span></span>
<span id="cb610-8"><a href="ensemble-learning.html#cb610-8" aria-hidden="true" tabindex="-1"></a>  yhat <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit, <span class="at">newdata=</span>df)</span>
<span id="cb610-9"><a href="ensemble-learning.html#cb610-9" aria-hidden="true" tabindex="-1"></a>  df<span class="sc">$</span>yr <span class="ot">&lt;-</span> df<span class="sc">$</span>yr <span class="sc">-</span> h<span class="sc">*</span>yhat <span class="co"># errors for the next iteration</span></span>
<span id="cb610-10"><a href="ensemble-learning.html#cb610-10" aria-hidden="true" tabindex="-1"></a>  YP <span class="ot">&lt;-</span> <span class="fu">cbind</span>(YP, h<span class="sc">*</span>yhat) <span class="co"># This is your main prediction added to YP </span></span>
<span id="cb610-11"><a href="ensemble-learning.html#cb610-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb610-12"><a href="ensemble-learning.html#cb610-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb610-13"><a href="ensemble-learning.html#cb610-13" aria-hidden="true" tabindex="-1"></a><span class="fu">viz</span>(<span class="dv">101</span>)</span></code></pre></div>
<p><img src="12-Ensemble_files/figure-html/en15-1.png" width="672" /></p>
<p>It overfits. Unlike random forests, boosting can overfit if the number of trees (B) and depth of each tree (D) are too large. By averaging over a large number of trees, bagging and random forests reduces variability. Boosting does not average over the trees.</p>
<p>This shows that <span class="math inline">\(h\)</span> should be tuned by a proper process. The generalized <a href="https://cran.r-project.org/web/packages/gbm/vignettes/gbm.pdf">boosted regression modeling (GBM)</a> <span class="citation">(<a href="#ref-Ridgeway_2020" role="doc-biblioref"><strong>Ridgeway_2020?</strong></a>)</span> can also be used for boosting regressions. Note that there are many arguments with their specific default values in the function. For example, <code>n.tree</code> (B) is 100 and <code>shrinkage</code> (<span class="math inline">\(h\)</span>) is 0.1. The <code>gbm()</code> function also has <code>interaction.depth</code> (D) specifying the maximum depth of each tree. When it is 1, the model is just an additive model, while 2 implies a model with up to 2-way interactions. A smaller <span class="math inline">\(h\)</span> typically requires more trees <span class="math inline">\(B\)</span>. It allows more and different shaped trees to attack the residuals.</p>
<p>Here is the application of <code>gbm</code> to our simulated data:</p>
<div class="sourceCode" id="cb611"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb611-1"><a href="ensemble-learning.html#cb611-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gbm)</span>
<span id="cb611-2"><a href="ensemble-learning.html#cb611-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb611-3"><a href="ensemble-learning.html#cb611-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Note bag.fraction = 1 (no CV).  The default is 0.5</span></span>
<span id="cb611-4"><a href="ensemble-learning.html#cb611-4" aria-hidden="true" tabindex="-1"></a>bo1 <span class="ot">&lt;-</span> <span class="fu">gbm</span>(y <span class="sc">~</span> x, <span class="at">distribution =</span> <span class="st">&quot;gaussian&quot;</span>, <span class="at">n.tree =</span> <span class="dv">100</span>, <span class="at">data =</span> df,</span>
<span id="cb611-5"><a href="ensemble-learning.html#cb611-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">shrinkage =</span> <span class="fl">0.1</span>, <span class="at">bag.fraction =</span> <span class="dv">1</span>)</span>
<span id="cb611-6"><a href="ensemble-learning.html#cb611-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb611-7"><a href="ensemble-learning.html#cb611-7" aria-hidden="true" tabindex="-1"></a>bo2 <span class="ot">&lt;-</span> <span class="fu">gbm</span>(y <span class="sc">~</span> x, <span class="at">distribution =</span> <span class="st">&quot;gaussian&quot;</span>, <span class="at">data =</span> df) <span class="co"># All default</span></span>
<span id="cb611-8"><a href="ensemble-learning.html#cb611-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb611-9"><a href="ensemble-learning.html#cb611-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df<span class="sc">$</span>x, df<span class="sc">$</span>y, <span class="at">ylab =</span> <span class="st">&quot;&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;&quot;</span>) <span class="co">#Data points</span></span>
<span id="cb611-10"><a href="ensemble-learning.html#cb611-10" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(df<span class="sc">$</span>x, <span class="fu">predict</span>(bo1, <span class="at">data =</span> df, <span class="at">n.trees =</span> t), <span class="at">type =</span> <span class="st">&quot;s&quot;</span>,</span>
<span id="cb611-11"><a href="ensemble-learning.html#cb611-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>) <span class="co">#line for without CV</span></span>
<span id="cb611-12"><a href="ensemble-learning.html#cb611-12" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(df<span class="sc">$</span>x, <span class="fu">predict</span>(bo2, <span class="at">n.trees =</span> t, <span class="at">data =</span> df), <span class="at">type =</span> <span class="st">&quot;s&quot;</span>,</span>
<span id="cb611-13"><a href="ensemble-learning.html#cb611-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;green&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>) <span class="co">#line with default parameters with CV</span></span></code></pre></div>
<p><img src="12-Ensemble_files/figure-html/en16-1.png" width="672" /></p>
<p>We will have more applications with <code>gbm</code> in the next chapter. We can also have a boosting application for classification problems. While the <code>gbm</code> function can be used for classification that requires a different distribution (“bernoulli” - logistic regression for 0-1 outcomes), there is a special boosting method for classification problems, AdaBoost.M1, which is what we will look at next.</p>
</div>
<div id="adaboost" class="section level3 hasAnchor" number="13.3.2">
<h3><span class="header-section-number">13.3.2</span> AdaBoost<a href="ensemble-learning.html#adaboost" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>One of the most popular boosting algorithm is <strong>AdaBost.M1</strong> due to Freund and Schpire (1997). We consider two-class problem where <span class="math inline">\(y \in\{-1,1\}\)</span>, which is a categorical outcome. With a set of predictor variables <span class="math inline">\(X\)</span>, a classifier <span class="math inline">\(\hat{m}_{b}(x)\)</span> at tree <span class="math inline">\(b\)</span> among B trees, produces a prediction taking the two values <span class="math inline">\(\{-1,1\}\)</span>.</p>
<p>To understand how AdaBoost works, let’s look at the algorithm step by step:</p>
<ol style="list-style-type: decimal">
<li>Select the number of trees B, and the tree depth D;</li>
<li>Set initial weights, <span class="math inline">\(w_i=1/n\)</span>, for each observation.</li>
<li>Fit a classification tree <span class="math inline">\(\hat{m}_{b}(x)\)</span> at <span class="math inline">\(b=1\)</span>, the first tree.</li>
<li>Calculate the following misclassification error for <span class="math inline">\(b=1\)</span>:</li>
</ol>
<p><span class="math display">\[
\mathbf{err}_{b=1}=\frac{\sum_{i=1}^{n} \mathbf{I}\left(y_{i} \neq \hat{m}_{b}\left(x_{i}\right)\right)}{n}
\]</span></p>
<ol start="4" style="list-style-type: decimal">
<li>By using this error, calculate</li>
</ol>
<p><span class="math display">\[
\alpha_{b}=0.5\log \left(\frac{1-e r r_{b}}{e r r_{b}}\right)
\]</span></p>
<p>For example, suppose <span class="math inline">\(err_b = 0.3\)</span>, then <span class="math inline">\(\alpha_{b}=0.5\text{log}(0.7/0.3)\)</span>, which is a log odds or <span class="math inline">\(\log (\text{success}/\text{failure})\)</span>.</p>
<ol start="5" style="list-style-type: decimal">
<li>If the observation <span class="math inline">\(i\)</span> is misclassified, update its weights, if not, use <span class="math inline">\(w_i\)</span> which is <span class="math inline">\(1/n\)</span>:</li>
</ol>
<p><span class="math display">\[
w_{i} \leftarrow w_{i} e^{\alpha_b}
\]</span></p>
<p>Let’s try some numbers:</p>
<div class="sourceCode" id="cb612"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb612-1"><a href="ensemble-learning.html#cb612-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Suppose err = 0.2, n=100</span></span>
<span id="cb612-2"><a href="ensemble-learning.html#cb612-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">100</span></span>
<span id="cb612-3"><a href="ensemble-learning.html#cb612-3" aria-hidden="true" tabindex="-1"></a>err <span class="ot">=</span> <span class="fl">0.2</span></span>
<span id="cb612-4"><a href="ensemble-learning.html#cb612-4" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.5</span> <span class="sc">*</span> <span class="fu">log</span>((<span class="dv">1</span> <span class="sc">-</span> err) <span class="sc">/</span> err)</span>
<span id="cb612-5"><a href="ensemble-learning.html#cb612-5" aria-hidden="true" tabindex="-1"></a>alpha</span></code></pre></div>
<pre><code>## [1] 0.6931472</code></pre>
<div class="sourceCode" id="cb614"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb614-1"><a href="ensemble-learning.html#cb614-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(alpha)</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>So, the new weight for the misclassified <span class="math inline">\(i\)</span> in the second tree (i.e., <span class="math inline">\(b=2\)</span> stump) will be</p>
<div class="sourceCode" id="cb616"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb616-1"><a href="ensemble-learning.html#cb616-1" aria-hidden="true" tabindex="-1"></a><span class="co"># For misclassified observations</span></span>
<span id="cb616-2"><a href="ensemble-learning.html#cb616-2" aria-hidden="true" tabindex="-1"></a>weight_miss <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">/</span> n) <span class="sc">*</span> (<span class="fu">exp</span>(alpha))</span>
<span id="cb616-3"><a href="ensemble-learning.html#cb616-3" aria-hidden="true" tabindex="-1"></a>weight_miss</span></code></pre></div>
<pre><code>## [1] 0.02</code></pre>
<div class="sourceCode" id="cb618"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb618-1"><a href="ensemble-learning.html#cb618-1" aria-hidden="true" tabindex="-1"></a><span class="co"># For correctly classified observations</span></span>
<span id="cb618-2"><a href="ensemble-learning.html#cb618-2" aria-hidden="true" tabindex="-1"></a>weight_corr <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">/</span> n) <span class="sc">*</span> (<span class="fu">exp</span>(<span class="sc">-</span>alpha))</span>
<span id="cb618-3"><a href="ensemble-learning.html#cb618-3" aria-hidden="true" tabindex="-1"></a>weight_corr</span></code></pre></div>
<pre><code>## [1] 0.005</code></pre>
<p>This shows that as the misclassification error goes up, it increases the weights for each misclassified observation and reduces the weights for correctly classified observations.</p>
<ol start="6" style="list-style-type: decimal">
<li>With this procedure, in each loop from <span class="math inline">\(b\)</span> to B, it applies <span class="math inline">\(\hat{m}_{b}(x)\)</span> to the data using updated weights <span class="math inline">\(w_i\)</span> in each <span class="math inline">\(b\)</span>:</li>
</ol>
<p><span class="math display">\[
\mathbf{err}_{b}=\frac{\sum_{i=1}^{n} w_{i} \mathbf{I}\left(y_{i} \neq \hat{m}_{b}\left(x_{i}\right)\right)}{\sum_{i=1}^{n} w_{i}}
\]</span></p>
<p>We normalize all weights between 0 and 1 so that sum of the weights would be one in each iteration. Hence, the algorithm works in a way that it randomly replicates the observations as new data points by using the weights as their probabilities. This process also resembles to under- and oversampling at the same time so that the number of observations stays the same. The new dataset now is used again for the next tree (<span class="math inline">\(b=2\)</span>) and this iteration continues until B. We can use <code>rpart</code> in each tree with <code>weights</code> option as we will shown momentarily.</p>
<p>Here is an example with the <code>myocarde</code> data that we only use the first 6 observations:</p>
<div class="sourceCode" id="cb620"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb620-1"><a href="ensemble-learning.html#cb620-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb620-2"><a href="ensemble-learning.html#cb620-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb620-3"><a href="ensemble-learning.html#cb620-3" aria-hidden="true" tabindex="-1"></a>myocarde <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">&quot;myocarde.csv&quot;</span>, <span class="at">delim =</span> <span class="st">&quot;;&quot;</span> ,</span>
<span id="cb620-4"><a href="ensemble-learning.html#cb620-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">escape_double =</span> <span class="cn">FALSE</span>, <span class="at">trim_ws =</span> <span class="cn">TRUE</span>,</span>
<span id="cb620-5"><a href="ensemble-learning.html#cb620-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb620-6"><a href="ensemble-learning.html#cb620-6" aria-hidden="true" tabindex="-1"></a>myocarde <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(myocarde)</span>
<span id="cb620-7"><a href="ensemble-learning.html#cb620-7" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">head</span>(myocarde)</span>
<span id="cb620-8"><a href="ensemble-learning.html#cb620-8" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Weights <span class="ot">=</span> <span class="dv">1</span> <span class="sc">/</span> <span class="fu">nrow</span>(df)</span>
<span id="cb620-9"><a href="ensemble-learning.html#cb620-9" aria-hidden="true" tabindex="-1"></a>df</span></code></pre></div>
<pre><code>##   FRCAR INCAR INSYS PRDIA PAPUL PVENT REPUL  PRONO   Weights
## 1    90  1.71  19.0    16  19.5  16.0   912 SURVIE 0.1666667
## 2    90  1.68  18.7    24  31.0  14.0  1476  DECES 0.1666667
## 3   120  1.40  11.7    23  29.0   8.0  1657  DECES 0.1666667
## 4    82  1.79  21.8    14  17.5  10.0   782 SURVIE 0.1666667
## 5    80  1.58  19.7    21  28.0  18.5  1418  DECES 0.1666667
## 6    80  1.13  14.1    18  23.5   9.0  1664  DECES 0.1666667</code></pre>
<p>Suppose that our first stump misclassifies the first observation. So the error rate</p>
<div class="sourceCode" id="cb622"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb622-1"><a href="ensemble-learning.html#cb622-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Alpha</span></span>
<span id="cb622-2"><a href="ensemble-learning.html#cb622-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">nrow</span>(df)</span>
<span id="cb622-3"><a href="ensemble-learning.html#cb622-3" aria-hidden="true" tabindex="-1"></a>err <span class="ot">=</span> <span class="dv">1</span> <span class="sc">/</span> n</span>
<span id="cb622-4"><a href="ensemble-learning.html#cb622-4" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.5</span> <span class="sc">*</span> <span class="fu">log</span>((<span class="dv">1</span> <span class="sc">-</span> err) <span class="sc">/</span> err)</span>
<span id="cb622-5"><a href="ensemble-learning.html#cb622-5" aria-hidden="true" tabindex="-1"></a>alpha</span></code></pre></div>
<pre><code>## [1] 0.804719</code></pre>
<div class="sourceCode" id="cb624"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb624-1"><a href="ensemble-learning.html#cb624-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(alpha)</span></code></pre></div>
<pre><code>## [1] 2.236068</code></pre>
<div class="sourceCode" id="cb626"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb626-1"><a href="ensemble-learning.html#cb626-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Weights for misclassified observations</span></span>
<span id="cb626-2"><a href="ensemble-learning.html#cb626-2" aria-hidden="true" tabindex="-1"></a>weight_miss <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">/</span> n) <span class="sc">*</span> (<span class="fu">exp</span>(alpha))</span>
<span id="cb626-3"><a href="ensemble-learning.html#cb626-3" aria-hidden="true" tabindex="-1"></a>weight_miss</span></code></pre></div>
<pre><code>## [1] 0.372678</code></pre>
<div class="sourceCode" id="cb628"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb628-1"><a href="ensemble-learning.html#cb628-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Weights for correctly classified observations</span></span>
<span id="cb628-2"><a href="ensemble-learning.html#cb628-2" aria-hidden="true" tabindex="-1"></a>weight_corr <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">/</span> n) <span class="sc">*</span> (<span class="fu">exp</span>(<span class="sc">-</span>alpha))</span>
<span id="cb628-3"><a href="ensemble-learning.html#cb628-3" aria-hidden="true" tabindex="-1"></a>weight_corr</span></code></pre></div>
<pre><code>## [1] 0.0745356</code></pre>
<p>Hence, our new sample weights</p>
<div class="sourceCode" id="cb630"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb630-1"><a href="ensemble-learning.html#cb630-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>New_weights <span class="ot">&lt;-</span> <span class="fu">c</span>(weight_miss, <span class="fu">rep</span>(weight_corr, <span class="dv">5</span>))</span>
<span id="cb630-2"><a href="ensemble-learning.html#cb630-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Norm_weights <span class="ot">&lt;-</span> df<span class="sc">$</span>New_weight <span class="sc">/</span> <span class="fu">sum</span>(df<span class="sc">$</span>New_weight) <span class="co"># normalizing</span></span>
<span id="cb630-3"><a href="ensemble-learning.html#cb630-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Not reporting X&#39;s for now</span></span>
<span id="cb630-4"><a href="ensemble-learning.html#cb630-4" aria-hidden="true" tabindex="-1"></a>df[, <span class="dv">8</span><span class="sc">:</span><span class="dv">11</span>]</span></code></pre></div>
<pre><code>##    PRONO   Weights New_weights Norm_weights
## 1 SURVIE 0.1666667   0.3726780          0.5
## 2  DECES 0.1666667   0.0745356          0.1
## 3  DECES 0.1666667   0.0745356          0.1
## 4 SURVIE 0.1666667   0.0745356          0.1
## 5  DECES 0.1666667   0.0745356          0.1
## 6  DECES 0.1666667   0.0745356          0.1</code></pre>
<p>We can see that the misclassified observation (the first one) has 5 times more likelihood than the other correctly classified observations. We now need to incorporate these weights and resample these six observations. Since incorrectly classified records have higher sample weights, the probability to select those records is very high.</p>
<p>If we use a simple tree as our base classifier, we can directly incorporate these weights into <code>rpart</code>. We can use other base classifier. In that case, we can do resampling with these probability weights:</p>
<div class="sourceCode" id="cb632"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb632-1"><a href="ensemble-learning.html#cb632-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb632-2"><a href="ensemble-learning.html#cb632-2" aria-hidden="true" tabindex="-1"></a>ind <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">6</span>, <span class="dv">6</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> df<span class="sc">$</span>Norm_weights)</span>
<span id="cb632-3"><a href="ensemble-learning.html#cb632-3" aria-hidden="true" tabindex="-1"></a>df[ind, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">9</span><span class="sc">:</span><span class="dv">12</span>)] <span class="co"># After</span></span></code></pre></div>
<pre><code>##     FRCAR INCAR INSYS PRDIA PAPUL PVENT REPUL  PRONO
## 1      90  1.71  19.0    16  19.5  16.0   912 SURVIE
## 5      80  1.58  19.7    21  28.0  18.5  1418  DECES
## 1.1    90  1.71  19.0    16  19.5  16.0   912 SURVIE
## 6      80  1.13  14.1    18  23.5   9.0  1664  DECES
## 2      90  1.68  18.7    24  31.0  14.0  1476  DECES
## 1.2    90  1.71  19.0    16  19.5  16.0   912 SURVIE</code></pre>
<p>As we can see, the misclassified observation is repeated three times in the new sample. Hence, observations that are misclassified will have more influence in the next classifier. <strong>This is an incredible boost that forces the classification tree to adjust its prediction to do better job for misclassified observations.</strong></p>
<ol start="7" style="list-style-type: decimal">
<li>Finally, in the output, the contributions from classifiers that fit the data better are given more weight (a larger <span class="math inline">\(\alpha_b\)</span> means a better fit). Unlike a random forest algorithm where each tree gets an equal weight in final decision, here some stumps get more say in final classification. Moreover, “forest of stumps” the order of trees is important.</li>
</ol>
<p>Hence, the final prediction on <span class="math inline">\(y_i\)</span> will be combined from all trees, <span class="math inline">\(b\)</span> to B, through a weighted majority vote:</p>
<p><span class="math display">\[
\hat{y}_{i}=\operatorname{sign}\left(\sum_{b=1}^{B} \alpha_{b} \hat{m}_{b}(x)\right),
\]</span></p>
<p>which is a signum function defined as follows:</p>
<p><span class="math display">\[
\operatorname{sign}(x):=\left\{\begin{array}{ll}
{-1} &amp; {\text { if } x&lt;0} \\
{0} &amp; {\text { if } x=0} \\
{1} &amp; {\text { if } x&gt;0}
\end{array}\right.
\]</span></p>
<p>Here is a simple simulation to show how <span class="math inline">\(\alpha_b\)</span> will make the importance of each tree (<span class="math inline">\(\hat{m}_{b}(x)\)</span>) different:</p>
<div class="sourceCode" id="cb634"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb634-1"><a href="ensemble-learning.html#cb634-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">1000</span></span>
<span id="cb634-2"><a href="ensemble-learning.html#cb634-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb634-3"><a href="ensemble-learning.html#cb634-3" aria-hidden="true" tabindex="-1"></a>err <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.01</span>), n, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb634-4"><a href="ensemble-learning.html#cb634-4" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">=</span> <span class="fl">0.5</span> <span class="sc">*</span> <span class="fu">log</span>((<span class="dv">1</span> <span class="sc">-</span> err) <span class="sc">/</span> err)</span>
<span id="cb634-5"><a href="ensemble-learning.html#cb634-5" aria-hidden="true" tabindex="-1"></a>ind <span class="ot">=</span> <span class="fu">order</span>(err)</span>
<span id="cb634-6"><a href="ensemble-learning.html#cb634-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb634-7"><a href="ensemble-learning.html#cb634-7" aria-hidden="true" tabindex="-1"></a>  err[ind],</span>
<span id="cb634-8"><a href="ensemble-learning.html#cb634-8" aria-hidden="true" tabindex="-1"></a>  alpha[ind],</span>
<span id="cb634-9"><a href="ensemble-learning.html#cb634-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">&quot;error (err)&quot;</span>,</span>
<span id="cb634-10"><a href="ensemble-learning.html#cb634-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">&quot;alpha&quot;</span>,</span>
<span id="cb634-11"><a href="ensemble-learning.html#cb634-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">&quot;o&quot;</span>,</span>
<span id="cb634-12"><a href="ensemble-learning.html#cb634-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb634-13"><a href="ensemble-learning.html#cb634-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">lwd =</span> <span class="dv">2</span></span>
<span id="cb634-14"><a href="ensemble-learning.html#cb634-14" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="12-Ensemble_files/figure-html/en24-1.png" width="672" /></p>
<p>We can see that when there is no misclassification error (<code>err</code> = 0), “alpha” will be a large positive number. When the classifier very weak and predicts as good as a random guess (<code>err</code> = 0.5), the importance of the classifier will be 0. If all the observations are incorrectly classified (<code>err</code> = 1), our alpha value will be a negative integer.</p>
<p>The AdaBoost.M1 is known as a “discrete classifier” because it directly calculates discrete class labels <span class="math inline">\(\hat{y}_i\)</span>, rather than predicted probabilities, <span class="math inline">\(\hat{p}_i\)</span>.</p>
<p>What type of classifier, <span class="math inline">\(\hat{m}_{b}(x)\)</span>, would we choose? Usually a “weak classifier” like a “stump” (a two terminal-node classification tree, i.e one split) would be enough. The <span class="math inline">\(\hat{m}_{b}(x)\)</span> choose one variable to form a stump that gives the lowest Gini index.</p>
<p>Here is our simple example with the <code>myocarde</code> data to show how we can boost a simple weak learner (stump) by using AdaBoost algorithm:</p>
<div class="sourceCode" id="cb635"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb635-1"><a href="ensemble-learning.html#cb635-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart)</span>
<span id="cb635-2"><a href="ensemble-learning.html#cb635-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb635-3"><a href="ensemble-learning.html#cb635-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Data</span></span>
<span id="cb635-4"><a href="ensemble-learning.html#cb635-4" aria-hidden="true" tabindex="-1"></a>myocarde <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">&quot;myocarde.csv&quot;</span>, <span class="at">delim =</span> <span class="st">&quot;;&quot;</span> ,</span>
<span id="cb635-5"><a href="ensemble-learning.html#cb635-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">escape_double =</span> <span class="cn">FALSE</span>, <span class="at">trim_ws =</span> <span class="cn">TRUE</span>,</span>
<span id="cb635-6"><a href="ensemble-learning.html#cb635-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb635-7"><a href="ensemble-learning.html#cb635-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb635-8"><a href="ensemble-learning.html#cb635-8" aria-hidden="true" tabindex="-1"></a>myocarde <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(myocarde)</span>
<span id="cb635-9"><a href="ensemble-learning.html#cb635-9" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> (myocarde[ , <span class="st">&quot;PRONO&quot;</span>] <span class="sc">==</span> <span class="st">&quot;SURVIE&quot;</span>) <span class="sc">*</span> <span class="dv">2</span> <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb635-10"><a href="ensemble-learning.html#cb635-10" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> myocarde[ , <span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>]</span>
<span id="cb635-11"><a href="ensemble-learning.html#cb635-11" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x, y)</span>
<span id="cb635-12"><a href="ensemble-learning.html#cb635-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb635-13"><a href="ensemble-learning.html#cb635-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Setting</span></span>
<span id="cb635-14"><a href="ensemble-learning.html#cb635-14" aria-hidden="true" tabindex="-1"></a>rnd <span class="ot">=</span> <span class="dv">100</span> <span class="co"># number of rounds</span></span>
<span id="cb635-15"><a href="ensemble-learning.html#cb635-15" aria-hidden="true" tabindex="-1"></a>m <span class="ot">=</span> <span class="fu">nrow</span>(x)</span>
<span id="cb635-16"><a href="ensemble-learning.html#cb635-16" aria-hidden="true" tabindex="-1"></a>whts <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span> <span class="sc">/</span> m, m) <span class="co"># initial weights</span></span>
<span id="cb635-17"><a href="ensemble-learning.html#cb635-17" aria-hidden="true" tabindex="-1"></a>st <span class="ot">&lt;-</span> <span class="fu">list</span>() <span class="co"># container to save all stumps</span></span>
<span id="cb635-18"><a href="ensemble-learning.html#cb635-18" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="at">mode =</span> <span class="st">&quot;numeric&quot;</span>, rnd) <span class="co"># container for alpha</span></span>
<span id="cb635-19"><a href="ensemble-learning.html#cb635-19" aria-hidden="true" tabindex="-1"></a>y_hat <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="at">mode =</span> <span class="st">&quot;numeric&quot;</span>, m) <span class="co"># container for final predictions</span></span>
<span id="cb635-20"><a href="ensemble-learning.html#cb635-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb635-21"><a href="ensemble-learning.html#cb635-21" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb635-22"><a href="ensemble-learning.html#cb635-22" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>rnd) {</span>
<span id="cb635-23"><a href="ensemble-learning.html#cb635-23" aria-hidden="true" tabindex="-1"></a>  st[[i]] <span class="ot">&lt;-</span> <span class="fu">rpart</span>(y <span class="sc">~</span>., <span class="at">data =</span> df, <span class="at">weights =</span> whts, <span class="at">maxdepth =</span> <span class="dv">1</span>, <span class="at">method =</span> <span class="st">&quot;class&quot;</span>)</span>
<span id="cb635-24"><a href="ensemble-learning.html#cb635-24" aria-hidden="true" tabindex="-1"></a>  yhat <span class="ot">&lt;-</span> <span class="fu">predict</span>(st[[i]], x, <span class="at">type =</span> <span class="st">&quot;class&quot;</span>)</span>
<span id="cb635-25"><a href="ensemble-learning.html#cb635-25" aria-hidden="true" tabindex="-1"></a>  yhat <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(yhat))</span>
<span id="cb635-26"><a href="ensemble-learning.html#cb635-26" aria-hidden="true" tabindex="-1"></a>  e <span class="ot">&lt;-</span> <span class="fu">sum</span>((yhat <span class="sc">!=</span> y) <span class="sc">*</span> whts)</span>
<span id="cb635-27"><a href="ensemble-learning.html#cb635-27" aria-hidden="true" tabindex="-1"></a>  <span class="co"># alpha</span></span>
<span id="cb635-28"><a href="ensemble-learning.html#cb635-28" aria-hidden="true" tabindex="-1"></a>  alpha[i] <span class="ot">&lt;-</span> <span class="fl">0.5</span> <span class="sc">*</span> <span class="fu">log</span>((<span class="dv">1</span> <span class="sc">-</span> e) <span class="sc">/</span> e)</span>
<span id="cb635-29"><a href="ensemble-learning.html#cb635-29" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Updating weights </span></span>
<span id="cb635-30"><a href="ensemble-learning.html#cb635-30" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Note that, for true predictions, (y * yhat) will be +, otherwise -</span></span>
<span id="cb635-31"><a href="ensemble-learning.html#cb635-31" aria-hidden="true" tabindex="-1"></a>  whts <span class="ot">&lt;-</span> whts <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span>alpha[i] <span class="sc">*</span> y <span class="sc">*</span> yhat)</span>
<span id="cb635-32"><a href="ensemble-learning.html#cb635-32" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Normalizing weights</span></span>
<span id="cb635-33"><a href="ensemble-learning.html#cb635-33" aria-hidden="true" tabindex="-1"></a>  whts <span class="ot">&lt;-</span> whts <span class="sc">/</span> <span class="fu">sum</span>(whts)</span>
<span id="cb635-34"><a href="ensemble-learning.html#cb635-34" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb635-35"><a href="ensemble-learning.html#cb635-35" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb635-36"><a href="ensemble-learning.html#cb635-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Using each stump for final predictions</span></span>
<span id="cb635-37"><a href="ensemble-learning.html#cb635-37" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>rnd) {</span>
<span id="cb635-38"><a href="ensemble-learning.html#cb635-38" aria-hidden="true" tabindex="-1"></a>  pred <span class="ot">=</span> <span class="fu">predict</span>(st[[i]], df, <span class="at">type =</span> <span class="st">&quot;class&quot;</span>)</span>
<span id="cb635-39"><a href="ensemble-learning.html#cb635-39" aria-hidden="true" tabindex="-1"></a>  pred <span class="ot">=</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(pred))</span>
<span id="cb635-40"><a href="ensemble-learning.html#cb635-40" aria-hidden="true" tabindex="-1"></a>  y_hat <span class="ot">=</span> y_hat <span class="sc">+</span> (alpha[i] <span class="sc">*</span> pred)</span>
<span id="cb635-41"><a href="ensemble-learning.html#cb635-41" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb635-42"><a href="ensemble-learning.html#cb635-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb635-43"><a href="ensemble-learning.html#cb635-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Let&#39;s see what y_hat is</span></span>
<span id="cb635-44"><a href="ensemble-learning.html#cb635-44" aria-hidden="true" tabindex="-1"></a>y_hat</span></code></pre></div>
<pre><code>##  [1]   3.132649  -4.135656  -4.290437   7.547707  -3.118702  -6.946686
##  [7]   2.551433   1.960603   9.363346   6.221990   3.012195   6.982287
## [13]   9.765139   8.053999   8.494254   7.454104   4.112493   5.838279
## [19]   4.918513   9.514860   9.765139  -3.519537  -3.172093  -7.134057
## [25]  -3.066699  -4.539863  -2.532759  -2.490742   5.412605   2.903552
## [31]   2.263095  -6.718090  -2.790474   6.813963  -5.131830   3.680202
## [37]   3.495350   3.014052  -7.435835   6.594157  -7.435835  -6.838387
## [43]   3.951168   5.091548  -3.594420   8.237515  -6.718090  -9.582674
## [49]   2.658501 -10.282682   4.490239   9.765139  -5.891116  -5.593352
## [55]   6.802687  -2.059754   2.832103   7.655197  10.635851   9.312842
## [61]  -5.804151   2.464149  -5.634676   1.938855   9.765139   7.023157
## [67]  -6.078756  -7.031840   5.651634  -1.867942   9.472835</code></pre>
<div class="sourceCode" id="cb637"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb637-1"><a href="ensemble-learning.html#cb637-1" aria-hidden="true" tabindex="-1"></a><span class="co"># sign() function</span></span>
<span id="cb637-2"><a href="ensemble-learning.html#cb637-2" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">sign</span>(y_hat)</span>
<span id="cb637-3"><a href="ensemble-learning.html#cb637-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb637-4"><a href="ensemble-learning.html#cb637-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Confusion matrix</span></span>
<span id="cb637-5"><a href="ensemble-learning.html#cb637-5" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(pred, y)</span></code></pre></div>
<pre><code>##     y
## pred -1  1
##   -1 29  0
##   1   0 42</code></pre>
<p>This is our in-sample confusion table. We can also see several stumps:</p>
<div class="sourceCode" id="cb639"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb639-1"><a href="ensemble-learning.html#cb639-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart.plot)</span>
<span id="cb639-2"><a href="ensemble-learning.html#cb639-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb639-3"><a href="ensemble-learning.html#cb639-3" aria-hidden="true" tabindex="-1"></a>plt <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">5</span>,<span class="dv">10</span>,<span class="dv">30</span>, <span class="dv">60</span>, <span class="dv">90</span>)</span>
<span id="cb639-4"><a href="ensemble-learning.html#cb639-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb639-5"><a href="ensemble-learning.html#cb639-5" aria-hidden="true" tabindex="-1"></a>p <span class="ot">=</span> <span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb639-6"><a href="ensemble-learning.html#cb639-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(plt)){</span>
<span id="cb639-7"><a href="ensemble-learning.html#cb639-7" aria-hidden="true" tabindex="-1"></a><span class="fu">prp</span>(st[[i]], <span class="at">type =</span> <span class="dv">2</span>, <span class="at">extra =</span> <span class="dv">1</span>, <span class="at">split.col =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb639-8"><a href="ensemble-learning.html#cb639-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">split.border.col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">box.col =</span> <span class="st">&quot;pink&quot;</span>)</span>
<span id="cb639-9"><a href="ensemble-learning.html#cb639-9" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="12-Ensemble_files/figure-html/en26-1.png" width="672" /></p>
<div class="sourceCode" id="cb640"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb640-1"><a href="ensemble-learning.html#cb640-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(p)</span></code></pre></div>
<p>Let’s see it with the <code>JOUSBoost</code> <a href="https://cran.r-project.org/web/packages/JOUSBoost/vignettes/JOUS.pdf">package</a>:</p>
<div class="sourceCode" id="cb641"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb641-1"><a href="ensemble-learning.html#cb641-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(JOUSBoost)</span>
<span id="cb641-2"><a href="ensemble-learning.html#cb641-2" aria-hidden="true" tabindex="-1"></a>ada <span class="ot">&lt;-</span> <span class="fu">adaboost</span>(<span class="fu">as.matrix</span>(x), y, <span class="at">tree_depth =</span> <span class="dv">1</span>, <span class="at">n_rounds =</span> rnd)</span>
<span id="cb641-3"><a href="ensemble-learning.html#cb641-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ada)</span></code></pre></div>
<pre><code>##                  Length Class  Mode   
## alphas           100    -none- numeric
## trees            100    -none- list   
## tree_depth         1    -none- numeric
## terms              3    terms  call   
## confusion_matrix   4    table  numeric</code></pre>
<div class="sourceCode" id="cb643"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb643-1"><a href="ensemble-learning.html#cb643-1" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(ada, x)</span>
<span id="cb643-2"><a href="ensemble-learning.html#cb643-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(pred, y)</span></code></pre></div>
<pre><code>##     y
## pred -1  1
##   -1 29  0
##   1   0 42</code></pre>
<p>These results provide in-sample predictions. When we use it in a real example, we can train AdaBoost.M1 by the tree depths (1 in our example) and the number of iterations (100 trees in our example).</p>
<p>An application is provided in the next chapter.</p>
</div>
<div id="xgboost" class="section level3 hasAnchor" number="13.3.3">
<h3><span class="header-section-number">13.3.3</span> XGBoost<a href="ensemble-learning.html#xgboost" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Extreme Gradient Boosting (XGBoost) the most efficient version of the gradient boosting framework by its capacity to implement parallel computation on a single machine. It can be used for regression and classification problems with two modes: linear models and tree learning algorithm. That means XGBoost can also be used for regularization in linear models (Section VIII). As decision trees are much better to catch a nonlinear link between predictors and outcome, comparison between two modes can provide quick information to the practitioner, specially in causal analyses, about the structure of alternative models.</p>
<p>The XGBoost has several unique advantages: its speed is measured as “10 times faster than the <code>gbm</code>” (see its <a href="https://xgboost.readthedocs.io/en/stable/R-package/xgboostPresentation.html">vignette</a>) and it accepts very efficient input data structures, such as a <em>sparse</em> matrix<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a>. This special input structure in <code>xgboost</code> requires some additional data preparation: a matrix input for the features and a vector for the response. Therefore, a matrix input of the features requires to encode our categorical variables. The matrix can also be selected several possible choices: a regular R matrix, a sparse matrix from the <code>Matrix</code> package, and its own class, <code>xgb.Matrix</code>.</p>
<p>We start with a regression example here and leave the classification example to the next chapter in boosting applications. We will use the <a href="https://www.tmwr.org/ames.html">Ames housing data</a> to see the best “predictors” of the sale price.</p>
<div class="sourceCode" id="cb645"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb645-1"><a href="ensemble-learning.html#cb645-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(xgboost)</span>
<span id="cb645-2"><a href="ensemble-learning.html#cb645-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mltools)</span>
<span id="cb645-3"><a href="ensemble-learning.html#cb645-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb645-4"><a href="ensemble-learning.html#cb645-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modeldata) <span class="co"># This can also be loaded by the tidymodels package</span></span>
<span id="cb645-5"><a href="ensemble-learning.html#cb645-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(ames)</span>
<span id="cb645-6"><a href="ensemble-learning.html#cb645-6" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(ames)</span></code></pre></div>
<pre><code>## [1] 2930   74</code></pre>
<p>Since, the <code>xgboost</code> algorithm accepts its input data as a matrix, all categorical variables have be one-hot coded, which creates a large matrix even with a small size data. That’s why using more memory efficient matrix types (sparse matrix etc.) speeds up the process. We ignore it here and use a regular R matrix, for now.</p>
<div class="sourceCode" id="cb647"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb647-1"><a href="ensemble-learning.html#cb647-1" aria-hidden="true" tabindex="-1"></a>ames_new <span class="ot">&lt;-</span> <span class="fu">one_hot</span>(<span class="fu">as.data.table</span>(ames))</span>
<span id="cb647-2"><a href="ensemble-learning.html#cb647-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(ames_new)</span>
<span id="cb647-3"><a href="ensemble-learning.html#cb647-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb647-4"><a href="ensemble-learning.html#cb647-4" aria-hidden="true" tabindex="-1"></a>ind <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(df), <span class="fu">nrow</span>(df), <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb647-5"><a href="ensemble-learning.html#cb647-5" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> df[ind,]</span>
<span id="cb647-6"><a href="ensemble-learning.html#cb647-6" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> df[<span class="sc">-</span>ind,]</span>
<span id="cb647-7"><a href="ensemble-learning.html#cb647-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb647-8"><a href="ensemble-learning.html#cb647-8" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(train[,<span class="sc">-</span><span class="fu">which</span>(<span class="fu">names</span>(train) <span class="sc">==</span> <span class="st">&quot;Sale_Price&quot;</span>)])</span>
<span id="cb647-9"><a href="ensemble-learning.html#cb647-9" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> train<span class="sc">$</span>Sale_Price</span></code></pre></div>
<p>Now we are ready for finding the optimal tuning parameters. One strategy in tuning is to see if there is a substantial difference between train and CV errors. We first start with the number of trees and the learning rate. If the difference still persists, we introduce regularization parameters. There are three regularization parameters: <code>gamma</code>, <code>lambda</code>, and <code>alpha</code>. The last two are similar to what we will see in regularization in Section VIII.</p>
<p>Here is our first run without a grid search. We will have a regression tree. The default booster is <code>gbtree</code> for tree-based models. For linear models it should be set to <code>gblinear</code>. The number of parameters and their combinations are very extensive in XGBoost. Please see them here: <a href="https://xgboost.readthedocs.io/en/latest/parameter.html#global-configuration" class="uri">https://xgboost.readthedocs.io/en/latest/parameter.html#global-configuration</a>. The combination of parameters we picked below is just an example.</p>
<div class="sourceCode" id="cb648"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb648-1"><a href="ensemble-learning.html#cb648-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb648-2"><a href="ensemble-learning.html#cb648-2" aria-hidden="true" tabindex="-1"></a>params <span class="ot">=</span> <span class="fu">list</span>(</span>
<span id="cb648-3"><a href="ensemble-learning.html#cb648-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">eta =</span> <span class="fl">0.1</span>, <span class="co"># Step size in boosting (default is 0.3)</span></span>
<span id="cb648-4"><a href="ensemble-learning.html#cb648-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">max_depth =</span> <span class="dv">3</span>, <span class="co"># maximum depth of the tree (default is 6)</span></span>
<span id="cb648-5"><a href="ensemble-learning.html#cb648-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">min_child_weight =</span> <span class="dv">3</span>, <span class="co"># minimum number of instances in each node</span></span>
<span id="cb648-6"><a href="ensemble-learning.html#cb648-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">subsample =</span> <span class="fl">0.8</span>, <span class="co"># Subsample ratio of the training instances</span></span>
<span id="cb648-7"><a href="ensemble-learning.html#cb648-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">colsample_bytree =</span> <span class="fl">1.0</span> <span class="co"># the fraction of columns to be subsampled</span></span>
<span id="cb648-8"><a href="ensemble-learning.html#cb648-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb648-9"><a href="ensemble-learning.html#cb648-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb648-10"><a href="ensemble-learning.html#cb648-10" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb648-11"><a href="ensemble-learning.html#cb648-11" aria-hidden="true" tabindex="-1"></a>boost <span class="ot">&lt;-</span> <span class="fu">xgb.cv</span>(</span>
<span id="cb648-12"><a href="ensemble-learning.html#cb648-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> X,</span>
<span id="cb648-13"><a href="ensemble-learning.html#cb648-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">label =</span> Y,</span>
<span id="cb648-14"><a href="ensemble-learning.html#cb648-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">nrounds =</span> <span class="dv">3000</span>, <span class="co"># the max number of iterations</span></span>
<span id="cb648-15"><a href="ensemble-learning.html#cb648-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">nthread =</span> <span class="dv">4</span>, <span class="co"># the number of CPU cores</span></span>
<span id="cb648-16"><a href="ensemble-learning.html#cb648-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">objective =</span> <span class="st">&quot;reg:squarederror&quot;</span>, <span class="co"># regression tree</span></span>
<span id="cb648-17"><a href="ensemble-learning.html#cb648-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">early_stopping_rounds =</span> <span class="dv">50</span>, <span class="co"># Stop if doesn&#39;t improve after 50 rounds </span></span>
<span id="cb648-18"><a href="ensemble-learning.html#cb648-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">nfold =</span> <span class="dv">10</span>, <span class="co"># 10-fold-CV</span></span>
<span id="cb648-19"><a href="ensemble-learning.html#cb648-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">params =</span> params,</span>
<span id="cb648-20"><a href="ensemble-learning.html#cb648-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">verbose =</span> <span class="dv">0</span> <span class="co">#silent</span></span>
<span id="cb648-21"><a href="ensemble-learning.html#cb648-21" aria-hidden="true" tabindex="-1"></a>)  </span></code></pre></div>
<p>Let’s see the RMSE and the best iteration:</p>
<div class="sourceCode" id="cb649"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb649-1"><a href="ensemble-learning.html#cb649-1" aria-hidden="true" tabindex="-1"></a>best_it <span class="ot">&lt;-</span> boost<span class="sc">$</span>best_iteration</span>
<span id="cb649-2"><a href="ensemble-learning.html#cb649-2" aria-hidden="true" tabindex="-1"></a>best_it</span></code></pre></div>
<pre><code>## [1] 1781</code></pre>
<div class="sourceCode" id="cb651"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb651-1"><a href="ensemble-learning.html#cb651-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(boost<span class="sc">$</span>evaluation_log<span class="sc">$</span>test_rmse_mean)</span></code></pre></div>
<pre><code>## [1] 16807.16</code></pre>
<div class="sourceCode" id="cb653"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb653-1"><a href="ensemble-learning.html#cb653-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One possible grid would be:</span></span>
<span id="cb653-2"><a href="ensemble-learning.html#cb653-2" aria-hidden="true" tabindex="-1"></a><span class="co"># param_grid &lt;- expand.grid(</span></span>
<span id="cb653-3"><a href="ensemble-learning.html#cb653-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   eta = 0.01,</span></span>
<span id="cb653-4"><a href="ensemble-learning.html#cb653-4" aria-hidden="true" tabindex="-1"></a><span class="co">#   max_depth = 3,</span></span>
<span id="cb653-5"><a href="ensemble-learning.html#cb653-5" aria-hidden="true" tabindex="-1"></a><span class="co">#   min_child_weight = 3,</span></span>
<span id="cb653-6"><a href="ensemble-learning.html#cb653-6" aria-hidden="true" tabindex="-1"></a><span class="co">#   subsample = 0.5,</span></span>
<span id="cb653-7"><a href="ensemble-learning.html#cb653-7" aria-hidden="true" tabindex="-1"></a><span class="co">#   colsample_bytree = 0.5,</span></span>
<span id="cb653-8"><a href="ensemble-learning.html#cb653-8" aria-hidden="true" tabindex="-1"></a><span class="co">#   gamma = c(0, 1, 10, 100, 1000),</span></span>
<span id="cb653-9"><a href="ensemble-learning.html#cb653-9" aria-hidden="true" tabindex="-1"></a><span class="co">#   lambda = seq(0, 0.01, 0.1, 1, 100, 1000),</span></span>
<span id="cb653-10"><a href="ensemble-learning.html#cb653-10" aria-hidden="true" tabindex="-1"></a><span class="co">#   alpha = c(0, 0.01, 0.1, 1, 100, 1000)</span></span>
<span id="cb653-11"><a href="ensemble-learning.html#cb653-11" aria-hidden="true" tabindex="-1"></a><span class="co">#   )</span></span>
<span id="cb653-12"><a href="ensemble-learning.html#cb653-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb653-13"><a href="ensemble-learning.html#cb653-13" aria-hidden="true" tabindex="-1"></a><span class="co"># After going through the grid in a loop with `xgb.cv`</span></span>
<span id="cb653-14"><a href="ensemble-learning.html#cb653-14" aria-hidden="true" tabindex="-1"></a><span class="co"># we save multiple `test_rmse_mean` and `best_iteration`</span></span>
<span id="cb653-15"><a href="ensemble-learning.html#cb653-15" aria-hidden="true" tabindex="-1"></a><span class="co"># and find the parameters that gives the minimum rmse</span></span></code></pre></div>
<p>Now after identifying the tuning parameters, we build the best model:</p>
<div class="sourceCode" id="cb654"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb654-1"><a href="ensemble-learning.html#cb654-1" aria-hidden="true" tabindex="-1"></a>tr_model <span class="ot">&lt;-</span> <span class="fu">xgboost</span>(</span>
<span id="cb654-2"><a href="ensemble-learning.html#cb654-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">params =</span> params,</span>
<span id="cb654-3"><a href="ensemble-learning.html#cb654-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> X,</span>
<span id="cb654-4"><a href="ensemble-learning.html#cb654-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">label =</span> Y,</span>
<span id="cb654-5"><a href="ensemble-learning.html#cb654-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">nrounds =</span> best_it,</span>
<span id="cb654-6"><a href="ensemble-learning.html#cb654-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">objective =</span> <span class="st">&quot;reg:squarederror&quot;</span>,</span>
<span id="cb654-7"><a href="ensemble-learning.html#cb654-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">verbose =</span> <span class="dv">0</span></span>
<span id="cb654-8"><a href="ensemble-learning.html#cb654-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p>We can obtain the top 10 influential features in our final model using the impurity (gain) metric:</p>
<div class="sourceCode" id="cb655"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb655-1"><a href="ensemble-learning.html#cb655-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vip)</span>
<span id="cb655-2"><a href="ensemble-learning.html#cb655-2" aria-hidden="true" tabindex="-1"></a><span class="fu">vip</span>(tr_model,</span>
<span id="cb655-3"><a href="ensemble-learning.html#cb655-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">aesthetics =</span> <span class="fu">list</span>(<span class="at">color =</span> <span class="st">&quot;green&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;orange&quot;</span>)) </span></code></pre></div>
<pre><code>## [20:08:45] WARNING: src/learner.cc:553: 
##   If you are loading a serialized model (like pickle in Python, RDS in R) generated by
##   older XGBoost, please export the model by calling `Booster.save_model` from that version
##   first, then load it back in current version. See:
## 
##     https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html
## 
##   for more details about differences between saving model and serializing.</code></pre>
<p><img src="12-Ensemble_files/figure-html/en33-1.png" width="672" /></p>
<p>Now, we can use our trained model for predictions using our test set. Note that, again, <code>xgboost</code> would only accept matrix inputs.</p>
<div class="sourceCode" id="cb657"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb657-1"><a href="ensemble-learning.html#cb657-1" aria-hidden="true" tabindex="-1"></a>yhat <span class="ot">&lt;-</span> <span class="fu">predict</span>(tr_model,</span>
<span id="cb657-2"><a href="ensemble-learning.html#cb657-2" aria-hidden="true" tabindex="-1"></a>                <span class="fu">as.matrix</span>(test[, <span class="sc">-</span><span class="fu">which</span>(<span class="fu">names</span>(test) <span class="sc">==</span> <span class="st">&quot;Sale_Price&quot;</span>)]))</span>
<span id="cb657-3"><a href="ensemble-learning.html#cb657-3" aria-hidden="true" tabindex="-1"></a>rmse_test <span class="ot">&lt;-</span></span>
<span id="cb657-4"><a href="ensemble-learning.html#cb657-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sqrt</span>(<span class="fu">mean</span>((test[, <span class="fu">which</span>(<span class="fu">names</span>(train) <span class="sc">==</span> <span class="st">&quot;Sale_Price&quot;</span>)] <span class="sc">-</span> yhat) <span class="sc">^</span> <span class="dv">2</span>))</span>
<span id="cb657-5"><a href="ensemble-learning.html#cb657-5" aria-hidden="true" tabindex="-1"></a>rmse_test</span></code></pre></div>
<pre><code>## [1] 23364.86</code></pre>
<p>Note the big difference between training and test RMSPE’s. This is an indication that our “example grid” is not doing a good job. We should include regularization tuning parameters and run a full scale grid search. We will look at a classification example in the next chapter (Chapter 13).</p>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="5">
<li id="fn5"><p><a href="https://web.archive.org/web/20121010030839/http://www.cs.princeton.edu/~schapire/papers/strengthofweak.pdf" class="uri">https://web.archive.org/web/20121010030839/http://www.cs.princeton.edu/~schapire/papers/strengthofweak.pdf</a><a href="ensemble-learning.html#fnref5" class="footnote-back">↩︎</a></p></li>
<li id="fn6"><p>In a sparse matrix, cells containing 0 are not stored in memory. Therefore, in a dataset mainly made of 0, the memory size is reduced.<a href="ensemble-learning.html#fnref6" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="cart.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ensemble-applications.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yaydede/toolbox/edit/master/12-Ensemble.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["YA_TextBook.pdf", "YA_TextBook.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
